import { defineSlide } from './_factory';

export const llamaCppIntro = defineSlide({
  id: 'llama-cpp-intro',
  type: 'two-column',
  options: {
    columnRatios: [0.5, 0.5],
  },
  content: {
    'pt-br': {
      title: 'llama.cpp: GGUF, Quantização e Inferência em CPU',
      body: `O **llama.cpp** é uma implementação de referência em **C/C++** para inferência de modelos Llama e derivados, desenvolvida originalmente por **Georgi Gerganov**.

O projeto surgiu da necessidade de transpor as barreiras impostas pelos frameworks de IA baseados em **Python**, focando em uma execução de **baixo nível** que prioriza a **portabilidade** e a **performance bruta** em hardware comum. Sob a liderança de **Gerganov**, a ferramenta evoluiu para se tornar a **base do ecossistema de modelos locais**, sendo a responsável pela criação e manutenção do formato **GGUF**, que hoje é o **padrão de mercado** para distribuição de LLMs quantizados.`,
    },
    'en-us': {
      title: 'llama.cpp: GGUF, Quantization and CPU Inference',
      body: `**llama.cpp** is a **C/C++** reference implementation for Llama model inference and derivatives, originally developed by **Georgi Gerganov**.

The project emerged from the need to overcome barriers imposed by AI frameworks based on **Python**, focusing on **low-level** execution that prioritizes **portability** and **raw performance** on common hardware. Under **Gerganov's** leadership, the tool evolved to become the **backbone of the local model ecosystem**, being responsible for creating and maintaining the **GGUF** format, which is now the **market standard** for distribution of quantized LLMs.`,
    },
  },
  visual: {
    id: 'llama-cpp-quant-explorer',
    copy: {
      'pt-br': {
        title: 'Explorador de Quantização GGUF',
        subtitle: 'Cálculo real de VRAM por modelo e formato',
        modelLabel: 'Modelo',
        formatLabel: 'Formato GGUF',
        vramTitle: 'VRAM Breakdown',
        vramFormula: '(bpp × params) / 8 + KV_cache',
        qualityTitle: 'Qualidade vs Tamanho',
        qualitySubtitle: 'Cada ponto é um formato GGUF',
        speedTitle: 'Velocidade por Backend',
        speedSubtitle: 'tok/s estimado por tamanho do modelo',
        stepperTitle: 'Pipeline de Inferência llama.cpp',
        stepFocusLabel: 'Foco',
        step1Label: 'mmap GGUF',
        step1Body: 'Arquivo mapeado em memória sem carregar tudo.',
        step2Label: 'Dequantização',
        step2Body: 'Blocos de 32 pesos dequantizados sob demanda.',
        step3Label: 'MatMul SIMD',
        step3Body: 'AVX2/NEON multiplicam matrizes em paralelo.',
        step4Label: 'Sample + KV',
        step4Body: 'Token amostrado e KV cache atualizado.',
        paramsLabel: 'Pesos',
        fileSizeLabel: 'Arquivo',
        kvCacheLabel: 'KV Cache',
        totalVramLabel: 'VRAM Total',
        bppLabel: 'Bits/Peso',
        speedLabel: 'Velocidade',
        tokUnit: 'tok/s',
        qualityLabel: 'Qualidade',
        fp16Reference: 'Linha de referência FP16',
        cpuSimdLabel: 'AVX2',
        metalLabel: 'Metal',
        cudaLabel: 'CUDA',
      },
      'en-us': {
        title: 'GGUF Quantization Explorer',
        subtitle: 'Real VRAM calculation per model and format',
        modelLabel: 'Model',
        formatLabel: 'GGUF Format',
        vramTitle: 'VRAM Breakdown',
        vramFormula: '(bpp × params) / 8 + KV_cache',
        qualityTitle: 'Quality vs Size',
        qualitySubtitle: 'Each point is a GGUF format',
        speedTitle: 'Speed per Backend',
        speedSubtitle: 'Estimated tok/s per model size',
        stepperTitle: 'llama.cpp Inference Pipeline',
        stepFocusLabel: 'Focus',
        step1Label: 'mmap GGUF',
        step1Body: 'File mapped in memory without loading everything.',
        step2Label: 'Dequantization',
        step2Body: 'Blocks of 32 weights dequantized on demand.',
        step3Label: 'MatMul SIMD',
        step3Body: 'AVX2/NEON multiply matrices in parallel.',
        step4Label: 'Sample + KV',
        step4Body: 'Token sampled and KV cache updated.',
        paramsLabel: 'Weights',
        fileSizeLabel: 'File Size',
        kvCacheLabel: 'KV Cache',
        totalVramLabel: 'Total VRAM',
        bppLabel: 'Bits/Weight',
        speedLabel: 'Speed',
        tokUnit: 'tok/s',
        qualityLabel: 'Quality',
        fp16Reference: 'FP16 reference line',
        cpuSimdLabel: 'AVX2',
        metalLabel: 'Metal',
        cudaLabel: 'CUDA',
      },
    },
  },
});
