import { defineSlide } from './_factory';

export const moeExpertVisualization = defineSlide({
  id: 'moe-expert-visualization',
  type: 'two-column',
  options: {
    columnRatios: [0.4, 0.6],
  },
  content: {
    'pt-br': {
      title: 'Visualizando a Especialização',
      body: `Como sabemos que os especialistas realmente se especializam? 

Ao analisar o mapa de ativação (heatmap) ao lado, observamos um padrão claro:

1. **Clusters de Ativação:** Tokens com funções gramaticais semelhantes (como Verbos) tendem a "votar" nos mesmos especialistas.
2. **Separação de Domínio:** A pontuação quase nunca ativa os mesmos especialistas que os substantivos.
3. **Eficiência de Roteamento:** O roteador aprendeu a mapear o espaço semântico da linguagem para a "equipe" de especialistas disponível.

> Este mapa foi gerado injetando diferentes tipos de tokens em uma camada MoE e registrando quais especialistas o roteador escolheu.`,
    },
    'en-us': {
      title: 'Visualizing Specialization',
      body: `How do we know that experts actually specialize?

By analyzing the activation map (heatmap) on the right, we observe a clear pattern:

1. **Activation Clusters:** Tokens with similar grammatical functions (like Verbs) tend to "vote" for the same experts.
2. **Domain Separation:** Punctuation almost never activates the same experts as nouns.
3. **Routing Efficiency:** The router has learned to map the semantic space of language to the available "team" of experts.

> This map was generated by injecting different types of tokens into an MoE layer and recording which experts the router chose.`,
    },
  },
  visual: {
    id: 'localized-image',
    copy: {
      'pt-br': {
        src: 'moeExpertMap',
        alt: 'Mapa de calor mostrando a ativação de especialistas por tipo de token',
        openLabel: 'Ampliar mapa de ativação',
        closeLabel: 'Fechar mapa',
      },
      'en-us': {
        src: 'moeExpertMap',
        alt: 'Heatmap showing expert activation by token type',
        openLabel: 'Enlarge activation map',
        closeLabel: 'Close map',
      },
    },
  },
});
