import { defineSlide } from './_factory';

export const orpoIntro = defineSlide({
  id: 'orpo-intro',
  type: 'two-column',
  options: { columnRatios: [0.43, 0.57] },
  content: {
    'pt-br': {
      title: 'ORPO: Preference Alignment sem Modelo de Referência',
      body: [
        '**ORPO** significa **Odds Ratio Preference Optimization**. O paper é *"ORPO: Monolithic Preference Optimization without Reference Model"*, de Jiwoo Hong, Noah Lee e James Thorne, publicado no EMNLP 2024.',
        '',
        '### Uma etapa, não duas',
        '',
        'No pipeline clássico:',
        '```text',
        'Base → SFT → DPO (com modelo de referência)',
        '```',
        '',
        'No ORPO:',
        '```text',
        'Base → ORPO (etapa única)',
        '```',
        '',
        'Ele junta duas coisas numa única loss:',
        '',
        '```text',
        'loss_ORPO = loss_SFT(chosen) + β · odds_ratio_penalty(chosen, rejected)',
        '```',
        '',
        'O modelo aprende a **imitar a resposta chosen** (como SFT) e ao mesmo tempo a **preferi-la sobre a rejected**.',
        '',
        '### Diferença crucial para DPO',
        '',
        '| DPO | ORPO |',
        '|---|---|',
        '| Parte de um modelo SFT | Parte do modelo base |',
        '| Usa modelo de referência congelado | Sem modelo de referência |',
        '| Só preference loss | SFT + preference na mesma loss |',
        '',
        '### Odds Ratio na prática',
        '',
        'O nome vem da razão de chances: o modelo deve aumentar a prob. da resposta escolhida e reduzir a da rejeitada para o mesmo prompt. O paper mostra que essa razão contrasta estilos favorecidos e desfavorecidos durante o SFT.',
        '',
        '### Três pipelines para comparar',
        '',
        '```text',
        'A) Base → SFT',
        'B) Base → SFT → DPO',
        'C) Base → ORPO',
        '```',
        '',
        'O ORPO foi desenhado como **substituto** de `SFT + alignment`, não como etapa extra em cima do SFT.',
        '',
        '> O dataset Valdoria ORPO/DPO segue o mesmo contrato: `{prompt, chosen, rejected}`. A diferença é como o algoritmo consome o par.',
      ].join('\n'),
    },
    'en-us': {
      title: 'ORPO: Preference Alignment without a Reference Model',
      body: [
        '**ORPO** stands for **Odds Ratio Preference Optimization**. The paper is *"ORPO: Monolithic Preference Optimization without Reference Model"* by Jiwoo Hong, Noah Lee, and James Thorne, published at EMNLP 2024.',
        '',
        '### One stage, not two',
        '',
        'Classic pipeline:',
        '```text',
        'Base → SFT → DPO (with reference model)',
        '```',
        '',
        'ORPO pipeline:',
        '```text',
        'Base → ORPO (single stage)',
        '```',
        '',
        'It combines two objectives in one loss:',
        '',
        '```text',
        'loss_ORPO = loss_SFT(chosen) + β · odds_ratio_penalty(chosen, rejected)',
        '```',
        '',
        'The model learns to **imitate the chosen response** (like SFT) and at the same time **prefer it over the rejected one**.',
        '',
        '### Key difference from DPO',
        '',
        '| DPO | ORPO |',
        '|---|---|',
        '| Starts from an SFT model | Starts from the base model |',
        '| Uses a frozen reference model | No reference model |',
        '| Preference loss only | SFT + preference in the same loss |',
        '',
        '### Odds Ratio in practice',
        '',
        'The name comes from the odds ratio: the model should increase the probability of the chosen response and decrease that of the rejected one for the same prompt. The paper shows this ratio contrasts favored and disfavored styles during SFT.',
        '',
        '### Three pipelines to compare',
        '',
        '```text',
        'A) Base → SFT',
        'B) Base → SFT → DPO',
        'C) Base → ORPO',
        '```',
        '',
        'ORPO was designed as a **replacement** for `SFT + alignment`, not as an extra stage on top of SFT.',
        '',
        '> The Valdoria ORPO/DPO dataset follows the same contract: `{prompt, chosen, rejected}`. The difference is how the algorithm consumes the pair.',
      ].join('\n'),
    },
  },
  visual: {
    id: 'code-tabs',
    copy: {
      'pt-br': {
        tabs: [{ label: 'ORPO' }],
        codePanels: [
          {
            title: 'Treinar Preference Alignment com ORPOTrainer',
            description: 'Carrega o modelo base, filtra exemplos inválidos do dataset e salva o modelo alinhado por ORPO.',
            source: { snippetId: 'sft_trl/orpo-train', language: 'python' },
            codeExplanations: [
              { lineRange: [1, 19], content: 'Importamos bibliotecas e definimos constantes: modelo base Qwen3.5-0.8B, dataset Valdoria ORPO e diretório de saída.' },
              { lineRange: [22, 56], content: 'is_valid_orpo_example() valida cada exemplo: exige prompt, chosen e rejected como listas não vazias, conteúdo não vazio e diferente entre chosen/rejected, e metadata.status opcionalmente igual a "kept".' },
              { lineRange: [59, 120], content: 'load_orpo_dataset() baixa o dataset, garante os splits train/eval, verifica colunas obrigatórias (prompt, chosen, rejected), filtra exemplos inválidos e aborta se algum split ficar vazio.' },
              { lineRange: [123, 129], content: 'main() cria a pasta de saída, fixa a seed e ativa TF32 se CUDA estiver disponível.' },
              { lineRange: [131, 161], content: 'Carregamos tokenizer (com left padding para preference training) e modelo base em bf16/fp16, com gradient_checkpointing ativado.' },
              { lineRange: [163, 215], content: 'ORPOConfig: learning_rate=1e-6 (conservador para não destruir o base), epochs=3, beta=0.1, batch efetivo 16, warmup_ratio, cosine scheduler, 8-bit optimizer e salvamento do melhor checkpoint.' },
              { lineRange: [217, 223], content: 'Montamos o ORPOTrainer sem modelo de referência — a principal diferença arquitetural para o DPO. Usamos processing_class=tokenizer.' },
              { lineRange: [225, 244], content: 'Auditamos parâmetros treináveis, treinamos, exibimos métricas finais e salvamos modelo + tokenizer alinhados.' },
            ],
          },
        ],
      },
      'en-us': {
        tabs: [{ label: 'ORPO' }],
        codePanels: [
          {
            title: 'Train Preference Alignment with ORPOTrainer',
            description: 'Loads the base model, filters invalid examples, and saves the ORPO-aligned model.',
            source: { snippetId: 'sft_trl/orpo-train', language: 'python' },
            codeExplanations: [
              { lineRange: [1, 19], content: 'We import libraries and define constants: base model Qwen3.5-0.8B, Valdoria ORPO dataset, and output directory.' },
              { lineRange: [22, 56], content: 'is_valid_orpo_example() validates each example: requires prompt/chosen/rejected as non-empty lists, non-empty and distinct chosen/rejected content, and optional metadata.status equal to "kept".' },
              { lineRange: [59, 120], content: 'load_orpo_dataset() downloads the dataset, ensures train/eval splits, checks required columns (prompt, chosen, rejected), filters invalid examples, and aborts if a split is empty.' },
              { lineRange: [123, 129], content: 'main() creates the output folder, sets the seed, and enables TF32 on CUDA.' },
              { lineRange: [131, 161], content: 'We load the tokenizer (with left padding for preference training) and the base model in bf16/fp16 with gradient_checkpointing enabled.' },
              { lineRange: [163, 215], content: 'ORPOConfig: learning_rate=1e-6 (conservative to preserve base behavior), epochs=3, beta=0.1, effective batch 16, warmup_ratio, cosine scheduler, 8-bit optimizer, best checkpoint saving.' },
              { lineRange: [217, 223], content: 'We build the ORPOTrainer with no reference model — the main architectural difference from DPO. Uses processing_class=tokenizer.' },
              { lineRange: [225, 244], content: 'We audit trainable parameters, train, print final metrics, and save the aligned model + tokenizer.' },
            ],
          },
        ],
      },
    },
  },
});
