import { defineSlide } from './_factory';

export const orpoIntro = defineSlide({
  id: 'orpo-intro',
  type: 'two-column',
  options: { columnRatios: [0.43, 0.57] },
  content: {
    'pt-br': {
      title: 'ORPO: Preference Alignment sem Modelo de Referência',
      body: [
        '**ORPO** significa **Odds Ratio Preference Optimization**. O paper é *"ORPO: Monolithic Preference Optimization without Reference Model"*, de Jiwoo Hong, Noah Lee e James Thorne, publicado no EMNLP 2024.',
        '',
        '### Uma etapa, não duas',
        '',
        'No pipeline clássico:',
        '```text',
        'Base → SFT → DPO (com modelo de referência)',
        '```',
        '',
        'No ORPO:',
        '```text',
        'Base → ORPO (etapa única)',
        '```',
        '',
        'Ele junta duas coisas numa única loss:',
        '',
        '```text',
        'loss_ORPO = loss_SFT(chosen) + β · odds_ratio_penalty(chosen, rejected)',
        '```',
        '',
        'O modelo aprende a **imitar a resposta chosen** (como SFT) e ao mesmo tempo a **preferi-la sobre a rejected**.',
        '',
        '### Diferença crucial para DPO',
        '',
        '| DPO | ORPO |',
        '|---|---|',
        '| Parte de um modelo SFT | Parte do modelo base |',
        '| Usa modelo de referência congelado | Sem modelo de referência |',
        '| Só preference loss | SFT + preference na mesma loss |',
        '',
        '### Odds Ratio na prática',
        '',
        'O nome vem da razão de chances: o modelo deve aumentar a prob. da resposta escolhida e reduzir a da rejeitada para o mesmo prompt. O paper mostra que essa razão contrasta estilos favorecidos e desfavorecidos durante o SFT.',
        '',
        '### Três pipelines para comparar',
        '',
        '```text',
        'A) Base → SFT',
        'B) Base → SFT → DPO',
        'C) Base → ORPO',
        '```',
        '',
        'O ORPO foi desenhado como **substituto** de `SFT + alignment`, não como etapa extra em cima do SFT.',
        '',
        '> O dataset Valdoria ORPO/DPO segue o mesmo contrato: `{prompt, chosen, rejected}`. A diferença é como o algoritmo consome o par.',
      ].join('\n'),
    },
    'en-us': {
      title: 'ORPO: Preference Alignment without a Reference Model',
      body: [
        '**ORPO** stands for **Odds Ratio Preference Optimization**. The paper is *"ORPO: Monolithic Preference Optimization without Reference Model"* by Jiwoo Hong, Noah Lee, and James Thorne, published at EMNLP 2024.',
        '',
        '### One stage, not two',
        '',
        'Classic pipeline:',
        '```text',
        'Base → SFT → DPO (with reference model)',
        '```',
        '',
        'ORPO pipeline:',
        '```text',
        'Base → ORPO (single stage)',
        '```',
        '',
        'It combines two objectives in one loss:',
        '',
        '```text',
        'loss_ORPO = loss_SFT(chosen) + β · odds_ratio_penalty(chosen, rejected)',
        '```',
        '',
        'The model learns to **imitate the chosen response** (like SFT) and at the same time **prefer it over the rejected one**.',
        '',
        '### Key difference from DPO',
        '',
        '| DPO | ORPO |',
        '|---|---|',
        '| Starts from an SFT model | Starts from the base model |',
        '| Uses a frozen reference model | No reference model |',
        '| Preference loss only | SFT + preference in the same loss |',
        '',
        '### Odds Ratio in practice',
        '',
        'The name comes from the odds ratio: the model should increase the probability of the chosen response and decrease that of the rejected one for the same prompt. The paper shows this ratio contrasts favored and disfavored styles during SFT.',
        '',
        '### Three pipelines to compare',
        '',
        '```text',
        'A) Base → SFT',
        'B) Base → SFT → DPO',
        'C) Base → ORPO',
        '```',
        '',
        'ORPO was designed as a **replacement** for `SFT + alignment`, not as an extra stage on top of SFT.',
        '',
        '> The Valdoria ORPO/DPO dataset follows the same contract: `{prompt, chosen, rejected}`. The difference is how the algorithm consumes the pair.',
      ].join('\n'),
    },
  },
  visual: {
    id: 'code-tabs',
    copy: {
      'pt-br': {
        tabs: [{ label: 'ORPO' }],
        codePanels: [
          {
            title: 'Treinar Preference Alignment com ORPOTrainer',
            description: 'Carrega o modelo base, consome pares de preferência e salva o modelo alinhado por ORPO.',
            source: { snippetId: 'sft_trl/orpo-train', language: 'python' },
            codeExplanations: [
              { lineRange: [1, 14], content: 'Importamos utilitários, ORPOConfig e ORPOTrainer com fallback para o módulo experimental do TRL.' },
              { lineRange: [17, 24], content: 'Definimos o modelo base, o dataset ORPO Valdoria, o diretório de saída e a seed fixa do experimento.' },
              { lineRange: [27, 52], content: 'make_orpo_config() filtra argumentos que a versão instalada do TRL não aceita, garantindo compatibilidade entre versões experimental e estável do ORPO.' },
              { lineRange: [55, 86], content: 'make_orpo_trainer() adapta a assinatura entre versões que usam processing_class vs tokenizer como parâmetro.' },
              { lineRange: [89, 112], content: 'Criamos a pasta de saída, fixamos a seed, ativamos TF32 quando houver CUDA, carregamos o dataset e montamos um split de avaliação se ele não vier pronto.' },
              { lineRange: [114, 142], content: 'Carregamos o modelo base (Qwen3.5-0.8B), não um checkpoint SFT. ORPO parte do modelo base, diferentemente do DPO que precisa de um checkpoint SFT.' },
              { lineRange: [144, 183], content: 'ORPOConfig: learning_rate mais alto que DPO porque o treino parte do base, epochs=3, beta=0.1 (odds ratio weight), batch efetivo 16, optimizer 8-bit, e salvamento do melhor checkpoint.' },
              { lineRange: [185, 191], content: 'Montamos o ORPOTrainer sem modelo de referência — essa é a principal diferença arquitetural para o DPO.' },
              { lineRange: [193, 204], content: 'Auditamos parâmetros treináveis, mostramos métricas, treinamos, salvamos modelo e tokenizer alinhados.' },
              { lineRange: [207, 208], content: 'Entrypoint padrão: executa main() quando o script é chamado diretamente.' },
            ],
          },
        ],
      },
      'en-us': {
        tabs: [{ label: 'ORPO' }],
        codePanels: [
          {
            title: 'Train Preference Alignment with ORPOTrainer',
            description: 'Loads the base model, consumes preference pairs, and saves the ORPO-aligned model.',
            source: { snippetId: 'sft_trl/orpo-train', language: 'python' },
            codeExplanations: [
              { lineRange: [1, 14], content: 'We import helpers, ORPOConfig, and ORPOTrainer with a fallback to the experimental TRL module.' },
              { lineRange: [17, 24], content: 'We define the base model, the Valdoria ORPO dataset, the output directory, and the fixed experiment seed.' },
              { lineRange: [27, 52], content: 'make_orpo_config() filters out arguments the installed TRL version does not accept, ensuring compatibility between experimental and stable ORPO versions.' },
              { lineRange: [55, 86], content: 'make_orpo_trainer() adapts the call signature between versions that use processing_class vs tokenizer as the parameter name.' },
              { lineRange: [89, 112], content: 'We create the output folder, set the seed, enable TF32 on CUDA, load the dataset, and create an eval split if one is not ready.' },
              { lineRange: [114, 142], content: 'We load the base model (Qwen3.5-0.8B), not an SFT checkpoint. ORPO starts from the base model, unlike DPO which requires an SFT checkpoint.' },
              { lineRange: [144, 183], content: 'ORPOConfig: higher LR than DPO because training starts from the base model, epochs=3, beta=0.1 (odds ratio weight), effective batch 16, 8-bit optimizer, best checkpoint saving.' },
              { lineRange: [185, 191], content: 'We build the ORPOTrainer with no reference model — this is the main architectural difference from DPO.' },
              { lineRange: [193, 204], content: 'We audit trainable parameters, show metrics, train, save the aligned model and tokenizer.' },
              { lineRange: [207, 208], content: 'Standard entrypoint: runs main() when the script is called directly.' },
            ],
          },
        ],
      },
    },
  },
});
