import { defineSlide } from './_factory';

export const preferenceAlignmentRlhf = defineSlide({
  id: 'preference-alignment-rlhf',
  type: 'two-column',
  options: { columnRatios: [0.5, 0.5] },
  content: {
    'pt-br': {
      title: 'Preference Alignment: de RLHF ao DPO',
      body: [
        'Depois do SFT, o modelo já sabe o formato da conversa e muitas respostas desejadas. Mas isso ainda não garante **preferência humana**: duas respostas podem estar corretas, e mesmo assim uma ser mais útil, mais segura, mais clara ou melhor calibrada.',
        '',
        'Foi daí que surgiu o **Preference Alignment**. Em vez de ensinar apenas “qual token vem depois”, começamos a ensinar **qual comportamento humanos preferem** quando comparam respostas candidatas para o mesmo prompt.',
        '',
        '### O dado de preferência',
        '',
        '- Mesmo prompt',
        '- Uma resposta `chosen`',
        '- Uma resposta `rejected`',
        '- O objetivo é empurrar o modelo para o estilo escolhido',
        '',
        'Na prática, isso muda o modelo em dimensões que SFT puro não resolve tão bem: **helpfulness**, qualidade de recusa, aderência a políticas, tom, concisão e obediência ao cânone quando há mais de uma continuação plausível.',
        '',
        '> SFT ensina “como responder”; alignment ensina “qual resposta é preferível entre várias possíveis”.',
      ].join('\n'),
      rightBody: [
        '### Pipeline histórico',
        '',
        '1. **SFT**: primeiro treinamos o modelo para seguir instruções.',
        '2. **Coleta de preferências humanas**: anotadores comparam duas ou mais respostas para o mesmo prompt.',
        '3. **Reward signal / reward model**: o sistema aprende um sinal de qualidade a partir dessas comparações.',
        '4. **Optimization step**: a política é ajustada para favorecer respostas mais bem avaliadas.',
        '',
        '### Onde entra o DPO',
        '',
        'O **RLHF clássico** ficou famoso com reward model + PPO, mas isso adiciona mais peças e mais instabilidade didática para explicar.',
        '',
        'O **DPO (Direct Preference Optimization)** mantém a mesma intuição de preferência, mas vai mais direto: ele compara `chosen` vs `rejected` **partindo do modelo SFT** e otimiza a política para preferir a resposta escolhida.',
        '',
        'Para o curso, isso é ideal: preserva a história correta do RLHF, mas nos leva para uma implementação moderna e prática, que é exatamente o que o próximo slide mostra.',
      ].join('\n'),
    },
    'en-us': {
      title: 'Preference Alignment: from RLHF to DPO',
      body: [
        'After SFT, the model already knows the chat format and many desired answer patterns. But that still does not guarantee **human preference**: two answers may both be correct, yet one is more helpful, safer, clearer, or better calibrated.',
        '',
        'That is where **Preference Alignment** came from. Instead of teaching only “which token comes next,” we started teaching **which behavior humans prefer** when comparing candidate answers for the same prompt.',
        '',
        '### Preference data',
        '',
        '- Same prompt',
        '- One `chosen` answer',
        '- One `rejected` answer',
        '- The objective is to push the model toward the preferred style',
        '',
        'In practice, this changes dimensions that pure SFT does not solve as well: **helpfulness**, refusal quality, policy adherence, tone, concision, and canon obedience when multiple continuations are plausible.',
        '',
        '> SFT teaches “how to answer”; alignment teaches “which answer is preferable among several valid ones”.',
      ].join('\n'),
      rightBody: [
        '### Historical pipeline',
        '',
        '1. **SFT**: first we train the model to follow instructions.',
        '2. **Human preference collection**: annotators compare two or more answers for the same prompt.',
        '3. **Reward signal / reward model**: the system learns a quality signal from those comparisons.',
        '4. **Optimization step**: the policy is adjusted to favor better-rated answers.',
        '',
        '### Where DPO fits',
        '',
        '**Classical RLHF** became famous with reward model + PPO, but that adds more moving parts and more teaching overhead.',
        '',
        '**DPO (Direct Preference Optimization)** keeps the same preference intuition, but goes more directly: it compares `chosen` vs `rejected` **starting from the SFT model** and optimizes the policy to prefer the chosen answer.',
        '',
        'For this course, that is ideal: it preserves the correct RLHF history while leading into a modern, practical implementation, which is exactly what the next slide shows.',
      ].join('\n'),
    },
  },
});
