import { defineSlide } from './_factory';

export const preferenceAlignmentRlhf = defineSlide({
  id: 'preference-alignment-rlhf',
  type: 'two-column',
  options: { columnRatios: [0.34, 0.66] },
  content: {
    'pt-br': {
      title: 'Preference Alignment: de RLHF ao DPO',
      body: [
        'Depois do SFT, o modelo já tem uma **política inicial boa**. O problema restante é decidir qual resposta deve vencer quando várias continuações parecem plausíveis.',
        '',
        'O **Preference Alignment** aprende com comparações humanas, não apenas com imitação do próximo token.',
        '',
        '### Contrato do dado',
        '',
        '- Mesmo `prompt`',
        '- Uma resposta `chosen`',
        '- Uma resposta `rejected`',
        '- O treino aumenta a margem a favor da escolhida',
        '',
        '### Da história à conta',
        '',
        'O **RLHF clássico** usa preferências, reward model e PPO. O **DPO** preserva a comparação humana, mas otimiza diretamente `chosen` contra `rejected`, ancorado na política SFT `π_ref`.',
        '',
        '> À direita, siga os tensores reais que entram na loss e voltam como gradiente.',
      ].join('\n'),
    },
    'en-us': {
      title: 'Preference Alignment: from RLHF to DPO',
      body: [
        'After SFT, the model already has a **good initial policy**. The remaining problem is deciding which answer should win when several continuations look plausible.',
        '',
        '**Preference Alignment** learns from human comparisons, not only from next-token imitation.',
        '',
        '### Data contract',
        '',
        '- Same `prompt`',
        '- One `chosen` answer',
        '- One `rejected` answer',
        '- Training increases the margin in favor of the chosen answer',
        '',
        '### From history to tensors',
        '',
        '**Classical RLHF** uses preferences, a reward model, and PPO. **DPO** keeps the human comparison but directly optimizes `chosen` against `rejected`, anchored to the SFT policy `π_ref`.',
        '',
        '> On the right, follow the real tensors entering the loss and returning as gradients.',
      ].join('\n'),
    },
  },
  visual: {
    id: 'dpo-preference-stepper',
    copy: {
      'pt-br': {
        title: 'DPO passo a passo',
        subtitle: 'Clique nos passos para seguir um único batch: [2B,T] → logits → log-probs → loss → gradiente.',
        promptLabel: 'Prompt',
        promptText: '“Um visitante com Carta de Entrada pode ficar 31 dias em Valdoria?”',
        chosenLabel: 'Chosen',
        chosenText: '“Não. Para 31 dias, precisa visto de permanência.”',
        rejectedLabel: 'Rejected',
        rejectedText: '“Sim. A Carta de Entrada cobre 31 dias.”',
        stepperTitle: 'Pipeline tensorial do DPO',
        previousLabel: 'Anterior',
        nextLabel: 'Próximo',
        progressLabel: 'Etapa',
        tensorLabel: 'Tensor ativo',
        shapeLabel: 'Shape',
        trainablePolicyLabel: 'Política treinável πθ',
        frozenReferenceLabel: 'Referência congelada π_ref',
        gradientDirectionLabel: 'Direção do gradiente',
        maskedTokenNote: '0 = token do prompt mascarado; valores negativos = log-probs da completion',
        frozenNoUpdateLabel: 'sem gradiente · sem update',
        chosenUpLabel: 'chosen log-prob ↑',
        rejectedDownLabel: 'rejected log-prob ↓',
        steps: [
          {
            label: 'Batch',
            title: 'Concatenar chosen e rejected',
            operation: 'cat([chosen, rejected]) → input_ids, completion_mask',
            description: 'As duas continuações entram no mesmo batch. A primeira linha é chosen; a segunda é rejected. A máscara marca somente os tokens cuja probabilidade participa da preferência.',
          },
          {
            label: 'Forward',
            title: 'Executar política e referência',
            operation: 'πθ(x), π_ref(x) → logits [2B,T,V] → shift [2B,T-1,V]',
            description: 'A política treinável mantém o grafo de autograd. A referência executa sem gradiente. O shift alinha cada posição com o token seguinte que ela deve prever.',
          },
          {
            label: 'Gather',
            title: 'Selecionar o log-prob de cada token',
            operation: 'log_softmax(logits,-1).gather(labels) × completion_mask',
            description: 'O eixo V desaparece quando gather seleciona a coluna do token observado. Prompt e padding são zerados pela máscara; sobram log-probs por token da resposta.',
          },
          {
            label: 'Reduce',
            title: 'Somar tokens e separar o par',
            operation: 'per_token_logps.sum(dim=1).chunk(2, dim=0)',
            description: 'A dimensão temporal é reduzida. O vetor [2B] volta a ser dois tensores [B]: um score de sequência para chosen e outro para rejected.',
          },
          {
            label: 'Loss',
            title: 'Construir a margem relativa DPO',
            operation: 'loss = -logsigmoid(β · [(πc-refc) - (πr-refr)])',
            description: 'A loss mede quanto a política prefere chosen sobre rejected além da preferência que já existia na referência SFT.',
          },
          {
            label: 'Update',
            title: 'Propagar e atualizar somente πθ',
            operation: 'loss.backward(); optimizer.step()',
            description: 'O gradiente aumenta a margem da política: favorece chosen e desfavorece rejected. A referência permanece congelada e não recebe update.',
          },
        ],
        takeawayTitle: 'O que o DPO realmente move',
        takeawayBody: 'Os números são didáticos, mas o contrato é real: somente πθ recebe gradientes; π_ref fornece a âncora relativa usada pela loss.',
      },
      'en-us': {
        title: 'DPO step by step',
        subtitle: 'Click through one batch: [2B,T] → logits → log-probs → loss → gradient.',
        promptLabel: 'Prompt',
        promptText: '“Can a visitor with an Entry Letter stay 31 days in Valdoria?”',
        chosenLabel: 'Chosen',
        chosenText: '“No. A 31-day stay requires a residence visa.”',
        rejectedLabel: 'Rejected',
        rejectedText: '“Yes. The Entry Letter covers 31 days.”',
        stepperTitle: 'DPO tensor pipeline',
        previousLabel: 'Previous',
        nextLabel: 'Next',
        progressLabel: 'Step',
        tensorLabel: 'Active tensor',
        shapeLabel: 'Shape',
        trainablePolicyLabel: 'Trainable policy πθ',
        frozenReferenceLabel: 'Frozen reference π_ref',
        gradientDirectionLabel: 'Gradient direction',
        maskedTokenNote: '0 = masked prompt token; negative values = completion log-probs',
        frozenNoUpdateLabel: 'no gradient · no update',
        chosenUpLabel: 'chosen log-prob ↑',
        rejectedDownLabel: 'rejected log-prob ↓',
        steps: [
          {
            label: 'Batch',
            title: 'Concatenate chosen and rejected',
            operation: 'cat([chosen, rejected]) → input_ids, completion_mask',
            description: 'Both continuations enter the same batch. The first row is chosen and the second is rejected. The mask marks only tokens whose probability participates in the preference.',
          },
          {
            label: 'Forward',
            title: 'Run policy and reference',
            operation: 'πθ(x), π_ref(x) → logits [2B,T,V] → shift [2B,T-1,V]',
            description: 'The trainable policy keeps its autograd graph. The reference runs without gradients. Shifting aligns each position with the next token it must predict.',
          },
          {
            label: 'Gather',
            title: 'Select each observed token log-prob',
            operation: 'log_softmax(logits,-1).gather(labels) × completion_mask',
            description: 'The V axis disappears when gather selects the observed token column. Prompt and padding are zeroed by the mask, leaving one log-prob per response token.',
          },
          {
            label: 'Reduce',
            title: 'Sum tokens and split the pair',
            operation: 'per_token_logps.sum(dim=1).chunk(2, dim=0)',
            description: 'The time dimension is reduced. The [2B] vector becomes two [B] tensors again: one sequence score for chosen and one for rejected.',
          },
          {
            label: 'Loss',
            title: 'Build the relative DPO margin',
            operation: 'loss = -logsigmoid(β · [(πc-refc) - (πr-refr)])',
            description: 'The loss measures how much more the policy prefers chosen over rejected beyond the preference already present in the SFT reference.',
          },
          {
            label: 'Update',
            title: 'Backpropagate and update only πθ',
            operation: 'loss.backward(); optimizer.step()',
            description: 'The gradient increases the policy margin: it favors chosen and disfavors rejected. The reference remains frozen and receives no update.',
          },
        ],
        takeawayTitle: 'What DPO actually moves',
        takeawayBody: 'The numbers are didactic, but the contract is real: only πθ receives gradients; π_ref supplies the relative anchor used by the loss.',
      },
    },
  },
});
