import { defineSlide } from './_factory';

export const pythonPrereqSumGenerator = defineSlide({
  id: 'python-prereq-sum-generator',
  type: 'two-column',
  options: {
    "columnRatios": [
      0.95,
      1.05
    ]
  },
  content: {
    'pt-br': {
      title: `Python Essencial: \`sum(...)\` com generator`,
      body: `Logo depois de list comprehension vem um padrão que aparece direto em código matemático: \`sum(...)\`.

1. **Mesma ideia do acumulador:** em vez de criar \`soma = 0\` e fazer \`+=\` no loop, entregamos ao Python os termos que devem ser somados.

2. **Sem colchetes:** em \`sum(x for x in dados)\`, a parte \`x for x in dados\` é uma generator expression.

3. **Ponte com a matemática:** o símbolo \`Σ\` significa “some todos estes termos”. Em Python, quase sempre isso vira \`sum(...)\`.

4. **Ponte direta com rede neural:** expressões como \`sum(w[i] * x[i] for i in range(n))\` aparecem o tempo todo em \`z = w^T x + b\`.

> Se list comprehension monta listas, \`sum(...)\` com generator monta uma soma.

### Tradução de matemática para código
\`\`\`txt
Σ idade_i        -> sum(idade for ...)
Σ w_i * x_i      -> sum(w[i] * x[i] for i in range(n))
\`\`\`

### Exemplo de rede neural
\`\`\`txt
z = Σ (w_i * x_i) + b
z = sum(w[i] * x[i] for i in range(n)) + b
\`\`\`

---

### Forma longa vs forma compacta
\`\`\`python
snippet:python-prereq/sum-generator
\`\`\`

- \`soma_idades\`: acumulador tradicional
- \`soma_idades_2\`: mesma conta com \`sum(...)\`
- leitura útil: “some \`idade\` para cada tupla em \`dados\`”`,
      codeExplanations: [
    {
    "lineRange": [
      1,
      1
    ],
    "content": "Usamos o mesmo dataset simples para manter o foco apenas na sintaxe da soma."
  },
    {
    "lineRange": [
      3,
      6
    ],
    "content": "A forma longa explicita o acumulador manual: começa em zero e soma uma idade por iteração."
  },
    {
    "lineRange": [
      9,
      9
    ],
    "content": "Aqui `sum(...)` faz a mesma conta recebendo os termos gerados pela expressão `idade for ...`."
  },
    {
    "lineRange": [
      11,
      12
    ],
    "content": "As duas impressões confirmam que a forma compacta preserva o mesmo resultado."
  }
  ],
    },
    'en-us': {
      title: `Python Essentials: \`sum(...)\` with a generator`,
      body: `Right after list comprehension comes a pattern that appears constantly in mathematical code: \`sum(...)\`.

1. **Same idea as the accumulator:** instead of creating \`total = 0\` and using \`+=\` in a loop, we give Python the terms that should be added.

2. **No brackets:** in \`sum(x for x in data)\`, the part \`x for x in data\` is a generator expression.

3. **Bridge to math:** the symbol \`Σ\` means “sum all these terms”. In Python, that almost always becomes \`sum(...)\`.

4. **Direct bridge to neural networks:** expressions like \`sum(w[i] * x[i] for i in range(n))\` appear constantly in \`z = w^T x + b\`.

> If list comprehension builds lists, \`sum(...)\` with a generator builds a sum.

### Translating math into code
\`\`\`txt
Σ age_i          -> sum(age for ...)
Σ w_i * x_i      -> sum(w[i] * x[i] for i in range(n))
\`\`\`

### Neural network example
\`\`\`txt
z = Σ (w_i * x_i) + b
z = sum(w[i] * x[i] for i in range(n)) + b
\`\`\`

---

### Long form vs compact form
\`\`\`python
snippet:python-prereq/sum-generator
\`\`\`

- \`sum_ages\`: classic accumulator
- \`sum_ages_2\`: the same calculation with \`sum(...)\`
- useful reading: “sum \`age\` for each tuple in \`data\`”`,
      codeExplanations: [
    {
    "lineRange": [
      1,
      1
    ],
    "content": "We reuse the same simple dataset so the focus stays on the summation syntax."
  },
    {
    "lineRange": [
      3,
      6
    ],
    "content": "The long form makes the manual accumulator explicit: start at zero and add one age per iteration."
  },
    {
    "lineRange": [
      9,
      9
    ],
    "content": "Here `sum(...)` performs the same calculation using the terms generated by `age for ...`."
  },
    {
    "lineRange": [
      11,
      12
    ],
    "content": "The two prints confirm that the compact form preserves the same result."
  }
  ],
    },
  },
});
