import { defineSlide } from './_factory';

export const ragIntroChromadb = defineSlide({
  id: 'rag-intro-chromadb',
  type: 'two-column',
  options: { columnRatios: [0.45, 0.55] },
  content: {
    'pt-br': {
      title: 'RAG: o LLM lê seus documentos antes de responder',
      body: [
        'No slide anterior vimos que o Sentence Transformer transforma qualquer frase em um vetor pronto para comparação. Mas para quê serve isso na prática?',
        '',
        'Imagine que você tem um processo judicial com dezenas de PDFs — petições, decisões, contratos. O conteúdo muda a cada movimentação. Treinar um LLM para "saber" tudo isso é caro, demorado e fica desatualizado na hora que o processo avança.',
        '',
        'A solução é não treinar. É deixar o LLM **ler** os documentos relevantes no momento em que a pergunta é feita. Isso se chama **RAG** — Retrieval-Augmented Generation.',
        '',
        '```text',
        'Pergunta → Busca semântica → Trechos relevantes → LLM gera resposta',
        '```',
        '',
        'O LLM não precisa "saber" tudo. Ele só precisa ler o contexto certo no momento certo.',
        '',
        '### ChromaDB',
        '',
        'ChromaDB é um banco de dados vetorial — ele armazena os vetores (embeddings) dos seus documentos e permite buscar por similaridade. Pense nele como um "Google dos seus PDFs": você pergunta em linguagem natural e ele devolve os trechos mais próximos semanticamente.',
        '',
        'O pipeline tem duas etapas:',
        '',
        '**1. Ingestão** — o primeiro snippet carrega PDFs, divide em pedaços (chunks), gera embeddings com o mesmo modelo do slide anterior (`e5-base`) e salva no ChromaDB.',
        '',
        '**2. Consulta** — o segundo snippet recebe uma pergunta, gera o embedding da query com o prefixo `"query: "`, busca os trechos mais similares no banco e manda tudo para um LLM local responder.',
        '',
        '> Note que usamos o mesmo `SentenceTransformer` para ingestão e para busca. O modelo precisa ser o mesmo porque os vetores estão no mesmo espaço semântico.',
      ].join('\n'),
    },
    'en-us': {
      title: 'RAG: the LLM reads your documents before answering',
      body: [
        'In the previous slide we saw that Sentence Transformers turn any sentence into a vector ready for comparison. But what is that useful for in practice?',
        '',
        'Imagine a judicial case with dozens of PDFs — petitions, rulings, contracts. The content changes with every filing. Training an LLM to "know" all of that is expensive, slow, and outdated the moment the case moves forward.',
        '',
        'The solution is not to train. It is to let the LLM **read** the relevant documents at the moment the question is asked. That is called **RAG** — Retrieval-Augmented Generation.',
        '',
        '```text',
        'Question → Semantic search → Relevant passages → LLM generates answer',
        '```',
        '',
        'The LLM does not need to "know" everything. It just needs to read the right context at the right time.',
        '',
        '### ChromaDB',
        '',
        'ChromaDB is a vector database — it stores document embeddings and allows similarity search. Think of it as a "Google for your PDFs": you ask in natural language and it returns the most semantically close passages.',
        '',
        'The pipeline has two stages:',
        '',
        '**1. Ingestion** — the first snippet loads PDFs, splits them into chunks, generates embeddings with the same model from the previous slide (`e5-base`), and saves them to ChromaDB.',
        '',
        '**2. Query** — the second snippet takes a question, generates the query embedding with the `"query: "` prefix, searches for the most similar passages, and sends everything to a local LLM to answer.',
        '',
        '> Note that we use the same `SentenceTransformer` for ingestion and query. The model must be the same because the vectors live in the same semantic space.',
      ].join('\n'),
    },
  },
  visual: {
    id: 'code-tabs',
    copy: {
      'pt-br': {
        tabs: [{ label: 'Ingestão' }, { label: 'Consulta' }],
        codePanels: [
          {
            title: 'Ingerir PDFs no ChromaDB com embeddings',
            description: 'Carrega PDFs de um processo judicial, divide em chunks, gera embeddings com e5-base e salva no banco vetorial.',
            source: { snippetId: 'rag/rag-ingest', language: 'python' },
            codeExplanations: [
              { lineRange: [1, 13], content: 'Importamos bibliotecas e definimos constantes: CNJ, diretórios de PDFs e do banco vetorial, modelo e5-base, e parâmetros de chunking (2500 chars com sobreposição de 300).' },
              { lineRange: [16, 22], content: 'limpar() normaliza texto extraído de PDF: remove null bytes, múltiplos espaços e quebras de linha excessivas.' },
              { lineRange: [25, 33], content: 'chunks() divide texto em pedaços de CHUNK_SIZE com sobreposição para não cortar termos. Cada pedaço vira um documento.' },
              { lineRange: [36, 55], content: 'extrair_pdf() abre cada página, extrai texto, divide em chunks e gera dict com id único, texto e metadados (arquivo, página, chunk, CNJ).' },
              { lineRange: [58, 61], content: 'main() cria diretório, carrega SentenceTransformer e conecta ao ChromaDB com PersistentClient.' },
              { lineRange: [63, 89], content: 'Para cada PDF: extrai chunks, gera embeddings com prefixo "passage: " e normalização, faz upsert no ChromaDB. Imprime caminho do banco ao final.' },
            ],
          },
          {
            title: 'Buscar contexto e gerar resposta com LLM local',
            description: 'Recebe uma pergunta, busca os trechos mais similares no ChromaDB com oversampling e deduplicação, e manda tudo para o LLM responder.',
            source: { snippetId: 'rag/rag-query', language: 'python' },
            codeExplanations: [
              { lineRange: [1, 36], content: 'Configuração: importamos bibliotecas e definimos constantes — CNJ, banco vetorial, modelo de embedding, URL do LLM, parâmetros de busca (8 resultados, oversampling 3x, 14000 chars máx) e kwargs do chat template.' },
              { lineRange: [39, 50], content: 'Carregamento global: SentenceTransformer e ChromaDB são carregados uma única vez no início, evitando reinicialização a cada pergunta.' },
              { lineRange: [53, 114], content: 'buscar_contexto() gera embedding da pergunta com prefixo "query: ", busca N_RESULTS × OVERSAMPLING resultados, deduplica por (arquivo, página, chunk), formata cada trecho com fonte e distância vetorial, e respeita o limite de caracteres.' },
              { lineRange: [117, 155], content: 'perguntar_llm() monta payload com system prompt (assistente jurídico, sem reasoning) e contexto + pergunta. Envia POST para o LLM local e retorna a resposta.' },
              { lineRange: [158, 229], content: 'rag() orquestra: busca contexto, verifica se há trechos, chama o LLM. Se vazio, retorna mensagem amigável. Interface terminal: loop infinito que lê perguntas, chama rag(), imprime resposta e fontes, com tratamento de erros. if __name__ inicia o loop interativo.' },
            ],
          },
        ],
      },
      'en-us': {
        tabs: [{ label: 'Ingestion' }, { label: 'Query' }],
        codePanels: [
          {
            title: 'Ingest PDFs into ChromaDB with embeddings',
            description: 'Loads PDFs from a judicial case, splits into chunks, generates embeddings with e5-base, and saves to the vector database.',
            source: { snippetId: 'rag/rag-ingest', language: 'python' },
            codeExplanations: [
              { lineRange: [1, 13], content: 'We import libraries and define constants: CNJ, PDF and database directories, e5-base model, and chunking parameters (2500 chars with 300 overlap).' },
              { lineRange: [16, 22], content: 'limpar() normalizes PDF-extracted text: removes null bytes, multiple spaces, and excessive line breaks.' },
              { lineRange: [25, 33], content: 'chunks() splits text into CHUNK_SIZE pieces with overlap to avoid cutting terms. Each piece becomes a document.' },
              { lineRange: [36, 55], content: 'extrair_pdf() opens each page, extracts text, splits into chunks, and generates a dict with unique id, text, and metadata (file, page, chunk, CNJ).' },
              { lineRange: [58, 61], content: 'main() creates directory, loads SentenceTransformer, and connects to ChromaDB with PersistentClient.' },
              { lineRange: [63, 89], content: 'For each PDF: extracts chunks, generates embeddings with "passage: " prefix and normalization, upserts to ChromaDB. Prints database path at the end.' },
            ],
          },
          {
            title: 'Search context and generate answer with local LLM',
            description: 'Takes a question, searches for the most similar passages in ChromaDB with oversampling and deduplication, and sends everything to the LLM to answer.',
            source: { snippetId: 'rag/rag-query', language: 'python' },
            codeExplanations: [
              { lineRange: [1, 36], content: 'Config: imports and constants — CNJ, vector database, embedding model, LLM URL, search parameters (8 results, 3x oversampling, 14000 max chars), and chat template kwargs.' },
              { lineRange: [39, 50], content: 'Global loading: SentenceTransformer and ChromaDB are loaded once at startup, avoiding re-initialization on every query.' },
              { lineRange: [53, 114], content: 'buscar_contexto() encodes the question with "query: " prefix, fetches N_RESULTS × OVERSAMPLING results, deduplicates by (file, page, chunk), formats each passage with source and vector distance, and respects the character limit.' },
              { lineRange: [117, 155], content: 'perguntar_llm() builds payload with system prompt (legal assistant, no reasoning) and context + question. Sends POST to local LLM and returns the answer.' },
              { lineRange: [158, 229], content: 'rag() orchestrates: fetches context, checks if passages exist, calls the LLM. If empty, returns a friendly message. Terminal interface: infinite loop that reads user questions, calls rag(), prints answer and sources. The if __name__ block starts the interactive loop.' },
            ],
          },
        ],
      },
    },
  },
});
