import { defineSlide } from './_factory';

export const ragIntroChromadb = defineSlide({
  id: 'rag-intro-chromadb',
  type: 'two-column',
  options: { columnRatios: [0.45, 0.55] },
  content: {
    'pt-br': {
      title: 'RAG: o LLM lê seus documentos antes de responder',
      body: [
        'No slide anterior vimos que o Sentence Transformer transforma qualquer frase em um vetor pronto para comparação. Mas para quê serve isso na prática?',
        '',
        '**RAG** significa **Retrieval-Augmented Generation**. A ideia é simples: em vez de mandar o LLM responder com o que ele memorizou do treinamento, a gente primeiro **recupera** os trechos mais relevantes dos seus próprios documentos e injeta no contexto da pergunta.',
        '',
        '```text',
        'Pergunta → Busca semântica → Trechos relevantes → LLM gera resposta',
        '```',
        '',
        'O LLM não precisa "saber" tudo. Ele só precisa ler o contexto certo no momento certo.',
        '',
        '### ChromaDB',
        '',
        'ChromaDB é um banco de dados vetorial — ele armazena os vetores (embeddings) dos seus documentos e permite buscar por similaridade. Pense nele como um "Google dos seus PDFs": você pergunta em linguagem natural e ele devolve os trechos mais próximos semanticamente.',
        '',
        'O pipeline tem duas etapas:',
        '',
        '**1. Ingestão** — o primeiro snippet carrega PDFs, divide em pedaços (chunks), gera embeddings com o mesmo modelo do slide anterior (`e5-base`) e salva no ChromaDB.',
        '',
        '**2. Consulta** — o segundo snippet recebe uma pergunta, gera o embedding da query com o prefixo `"query: "`, busca os 8 trechos mais similares no banco e manda tudo para um LLM local responder.',
        '',
        '> Note que usamos o mesmo `SentenceTransformer` para ingestão e para busca. O modelo precisa ser o mesmo porque os vetores estão no mesmo espaço semântico.',
      ].join('\n'),
      rightBody: [
        '```python',
        'snippet:rag/rag-ingest',
        '```',
      ].join('\n'),
      codeExplanations: [
        { lineRange: [1, 13], content: 'Importamos as bibliotecas e definimos constantes: número do processo CNJ, diretórios de PDFs e do banco vetorial, modelo de embedding, e parâmetros de chunking (pedaço de 2500 caracteres com sobreposição de 300).' },
        { lineRange: [16, 22], content: 'A função limpar() normaliza o texto extraído do PDF: remove null bytes, múltiplos espaços e quebras de linha excessivas.' },
        { lineRange: [25, 33], content: 'A função chunks() divide o texto em pedaços de CHUNK_SIZE caracteres com sobreposição de CHUNK_OVERLAP para não cortar termos no meio. Cada pedaço vira um documento separado.' },
        { lineRange: [36, 55], content: 'A função extrair_pdf() abre cada página do PDF, extrai o texto, divide em chunks e gera um dicionário com id único, texto e metadados (arquivo, página, número do chunk, CNJ).' },
        { lineRange: [58, 61], content: 'O main() cria o diretório do banco, carrega o SentenceTransformer e conecta ao ChromaDB com PersistentClient — o banco persiste no disco entre execuções.' },
        { lineRange: [63, 87], content: 'Para cada PDF, extrai os chunks, gera embeddings com o prefixo "passage: " e normalização, e faz upsert no ChromaDB — documentos novos são inseridos, existentes são atualizados. No final imprime o caminho do banco criado.' },
      ],
    },
    'en-us': {
      title: 'RAG: the LLM reads your documents before answering',
      body: [
        'In the previous slide we saw that Sentence Transformers turn any sentence into a vector ready for comparison. But what is that useful for in practice?',
        '',
        '**RAG** stands for **Retrieval-Augmented Generation**. The idea is simple: instead of sending the LLM to answer from what it memorized during training, we first **retrieve** the most relevant passages from your own documents and inject them into the question context.',
        '',
        '```text',
        'Question → Semantic search → Relevant passages → LLM generates answer',
        '```',
        '',
        'The LLM does not need to "know" everything. It just needs to read the right context at the right time.',
        '',
        '### ChromaDB',
        '',
        'ChromaDB is a vector database — it stores document embeddings and allows similarity search. Think of it as a "Google for your PDFs": you ask in natural language and it returns the most semantically close passages.',
        '',
        'The pipeline has two stages:',
        '',
        '**1. Ingestion** — the first snippet loads PDFs, splits them into chunks, generates embeddings with the same model from the previous slide (`e5-base`), and saves them to ChromaDB.',
        '',
        '**2. Query** — the second snippet takes a question, generates the query embedding with the `"query: "` prefix, searches for the 8 most similar passages, and sends everything to a local LLM to answer.',
        '',
        '> Note that we use the same `SentenceTransformer` for ingestion and query. The model must be the same because the vectors live in the same semantic space.',
      ].join('\n'),
      rightBody: [
        '```python',
        'snippet:rag/rag-ingest',
        '```',
      ].join('\n'),
      codeExplanations: [
        { lineRange: [1, 13], content: 'We import libraries and define constants: the CNJ case number, PDF and database directories, the embedding model, and chunking parameters (2500-char pieces with 300-char overlap).' },
        { lineRange: [16, 22], content: 'The limpar() function normalizes PDF-extracted text: removes null bytes, multiple spaces, and excessive line breaks.' },
        { lineRange: [25, 33], content: 'The chunks() function splits text into pieces of CHUNK_SIZE characters with CHUNK_OVERLAP to avoid cutting terms in the middle. Each piece becomes a separate document.' },
        { lineRange: [36, 55], content: 'The extrair_pdf() function opens each PDF page, extracts text, splits into chunks, and generates a dictionary with a unique id, text, and metadata (file, page, chunk number, CNJ).' },
        { lineRange: [58, 61], content: 'The main() function creates the database directory, loads the SentenceTransformer, and connects to ChromaDB with PersistentClient — the database persists to disk between runs.' },
        { lineRange: [63, 87], content: 'For each PDF, it extracts chunks, generates embeddings with the "passage: " prefix and normalization, and upserts to ChromaDB — new documents are inserted, existing ones are updated. Prints the database path when done.' },
      ],
    },
  },
  visual: {
    id: 'code-tabs',
    copy: {
      'pt-br': {
        tabs: [{ label: 'Consulta (RAG)' }],
        codePanels: [
          {
            title: 'Buscar contexto e gerar resposta com LLM local',
            description: 'Recebe uma pergunta, busca os trechos mais similares no ChromaDB e manda tudo para o LLM responder.',
            source: { snippetId: 'rag/rag-query', language: 'python' },
            codeExplanations: [
              { lineRange: [1, 11], content: 'Importamos bibliotecas e definimos constantes: banco vetorial, modelo de embedding, URL do LLM local, e parâmetros de busca (8 resultados, máximo de 14000 caracteres de contexto).' },
              { lineRange: [14, 19], content: 'A função limpar_think() remove tags <think> do LLM — necessária porque alguns modelos de raciocínio expõem o raciocínio interno antes da resposta final.' },
              { lineRange: [22, 50], content: 'A função buscar_contexto() carrega o SentenceTransformer, conecta ao ChromaDB, gera o embedding da pergunta com o prefixo "query: ", busca os N_RESULTS trechos mais similares e formata cada um com sua fonte (arquivo e página).' },
              { lineRange: [53, 106], content: 'A função perguntar_llm() monta o payload com system prompt (assistente jurídico que responde só com o contexto fornecido, sem reasoning) e a mensagem com o contexto concatenado e a pergunta do usuário. A função rag() orquestra tudo: busca o contexto e passa para o LLM. O bloco if __name__ lê a pergunta do terminal e imprime a resposta.' },
            ],
          },
        ],
      },
      'en-us': {
        tabs: [{ label: 'Query (RAG)' }],
        codePanels: [
          {
            title: 'Search context and generate answer with local LLM',
            description: 'Takes a question, searches for the most similar passages in ChromaDB, and sends everything to the LLM to answer.',
            source: { snippetId: 'rag/rag-query', language: 'python' },
            codeExplanations: [
              { lineRange: [1, 11], content: 'We import libraries and define constants: the vector database, embedding model, local LLM URL, and search parameters (8 results, 14000 max context characters).' },
              { lineRange: [14, 19], content: 'The limpar_think() function removes <think> tags from the LLM — necessary because some reasoning models expose internal reasoning before the final answer.' },
              { lineRange: [22, 50], content: 'The buscar_contexto() function loads SentenceTransformer, connects to ChromaDB, generates the question embedding with the "query: " prefix, searches for the N_RESULTS most similar passages, and formats each one with its source (file and page).' },
              { lineRange: [53, 106], content: 'The perguntar_llm() function builds the payload with a system prompt (legal assistant that answers only from provided context, no reasoning) and the message with concatenated context and user question. The rag() function orchestrates everything: fetches context and passes it to the LLM. The if __name__ block reads the question from the terminal and prints the answer.' },
            ],
          },
        ],
      },
    },
  },
});
