import { defineSlide } from './_factory';

export const sentenceTransformersIntro = defineSlide({
  id: 'sentence-transformers-intro',
  type: 'two-column',
  options: { columnRatios: [0.5, 0.5] },
  content: {
    'pt-br': {
      title: 'Sentence Transformers: embedding de frases para comparar significado',
      body: [
        'Nem todo embedding serve para comparar frases. O residual stream do GPT-2 ou as hidden states do BERT produzem um vetor **por token** — não um vetor único para a frase inteira. Para comparar semanticamente duas frases, precisamos de um modelo feito para isso.',
        '',
        '### Sentence Transformers (SBERT)',
        '',
        'SBERT fine-tuna BERT/RoBERTa com **pares de frases** similares e dissimilares (contraste). O resultado é um modelo que transforma qualquer frase em um único vetor que pode ser comparado por **similaridade de cosseno** (dot product com vetores normalizados).',
        '',
        '### Modelo multilingual e5-base',
        '',
        'O modelo `intfloat/multilingual-e5-base` cobre português, inglês e dezenas de outros idiomas. Ele espera um prefixo no texto:',
        '',
        '- `"passage: "` para o documento/texto base',
        '- `"query: "` para a pergunta (usado em retrieval)',
        '',
        '### O que o código mostra',
        '',
        'O snippet ao lado carrega o modelo, define uma frase base do direito ("O autor pede indenização por danos morais") e 7 frases de teste de temas variados.',
        '',
        'Depois calcula similaridade de duas formas:',
        '',
        '**Sem centrar:** o dot product bruto entre o embedding da base e de cada frase. Frases do mesmo domínio (direito) aparecem no topo, mas tópicos totalmente diferentes (baleia, bolo, RTX) ainda pontuam relativamente alto porque o espaço semântico global tem um viés de posicionamento.',
        '',
        '**Com centering:** subtraímos a média de **todos os vetores** (o "centro" do corpus) e renormalizamos. Isso remove o viés geral de posicionamento:',
        '',
        '```text',
        'base_c = (vetor - centro) / ||vetor - centro||',
        '```',
        '',
        'Agora a similaridade reflete a **direção da diferença** entre as frases, não a proximidade absoluta. Frases de domínios irrelevantes vão para próximo de zero ou negativo, e as juridicamente relevantes ganham ainda mais contraste.',
        '',
        '> Essa técnica de centering é usada em pipelines de retrieval para melhorar a separação entre chunks relevantes e irrelevantes.',
      ].join('\n'),
      rightBody: [
        '```python',
        'snippet:sentence-transformers/sentence-transformers-intro',
        '```',
      ].join('\n'),
      codeExplanations: [
        { lineRange: [1, 4], content: 'Importamos a biblioteca SentenceTransformer e numpy, e carregamos o modelo multilingual e5-base. O download acontece na primeira execução via Hugging Face Hub.' },
        { lineRange: [6, 18], content: 'Definimos uma frase base do direito brasileiro e 7 frases de teste cobrindo temas variados: jurídico (3), biologia, hardware, zoologia e culinária.' },
        { lineRange: [19, 25], content: 'A função `emb()` adiciona o prefixo `"passage: "` exigido pelo e5 para textos de referência e normaliza o embedding para que o dot product seja equivalente à similaridade de cosseno.' },
        { lineRange: [26, 41], content: 'Calculamos o embedding de todas as frases e medimos similaridade por dot product bruto. As frases jurídicas aparecem no topo, mas assuntos totalmente distintos ainda pontuam alto — o espaço semântico tem um viés geral.' },
        { lineRange: [43, 62], content: 'Subtraímos o vetor médio (centro do corpus) de cada embedding e renormalizamos. Isso remove o viés de posicionamento: frases irrelevantes caem para próximo de zero ou negativo, e a separação semântica fica mais nítida.' },
      ],
    },
    'en-us': {
      title: 'Sentence Transformers: embedding sentences to compare meaning',
      body: [
        'Not every embedding is suited for comparing sentences. The GPT-2 residual stream or BERT hidden states produce one vector **per token** — not a single vector for the whole sentence. To compare two sentences semantically, we need a model built for that.',
        '',
        '### Sentence Transformers (SBERT)',
        '',
        'SBERT fine-tunes BERT/RoBERTa on **sentence pairs** (similar and dissimilar via contrastive learning). The result is a model that maps any sentence into a single vector comparable by **cosine similarity** (dot product with normalized vectors).',
        '',
        '### Multilingual e5-base model',
        '',
        'The `intfloat/multilingual-e5-base` model covers Portuguese, English, and dozens of other languages. It expects a prefix:',
        '',
        '- `"passage: "` for the base text/document',
        '- `"query: "` for the question (used in retrieval)',
        '',
        '### What the code shows',
        '',
        'The snippet loads the model, defines a base legal sentence, and 7 test sentences on varied topics.',
        '',
        'Then it computes similarity in two ways:',
        '',
        '**Without centering:** raw dot product between the base embedding and each sentence. Same-domain sentences (legal) rank at the top, but completely unrelated topics (whale, cake, RTX) still score relatively high because the global semantic space has a positioning bias.',
        '',
        '**With centering:** we subtract the mean of **all vectors** (the corpus "center") and renormalize. This removes the global positioning bias:',
        '',
        '```text',
        'base_c = (vector - center) / ||vector - center||',
        '```',
        '',
        'Now similarity reflects the **direction of difference** between sentences, not their absolute proximity. Irrelevant domains drop to near zero or negative, while legally relevant ones gain even more contrast.',
        '',
        '> This centering technique is used in retrieval pipelines to improve the separation between relevant and irrelevant chunks.',
      ].join('\n'),
      rightBody: [
        '```python',
        'snippet:sentence-transformers/sentence-transformers-intro',
        '```',
      ].join('\n'),
      codeExplanations: [
        { lineRange: [1, 4], content: 'We import SentenceTransformer and numpy, and load the multilingual e5-base model. The download happens on first run via the Hugging Face Hub.' },
        { lineRange: [6, 18], content: 'We define a base Brazilian legal sentence and 7 test sentences covering varied topics: legal (3), biology, hardware, zoology, and baking.' },
        { lineRange: [19, 25], content: 'The `emb()` function adds the `"passage: "` prefix required by e5 for reference texts and normalizes the embedding so that dot product equals cosine similarity.' },
        { lineRange: [26, 41], content: 'We compute embeddings for all sentences and measure similarity via raw dot product. Legal sentences rank at the top, but unrelated topics still score relatively high — the semantic space has a global bias.' },
        { lineRange: [43, 62], content: 'We subtract the mean vector (corpus center) from each embedding and renormalize. This removes the positioning bias: irrelevant sentences drop to near zero or negative, making semantic separation sharper.' },
      ],
    },
  },
});
