import { defineSlide } from './_factory';

export const sentenceTransformersIntro = defineSlide({
  id: 'sentence-transformers-intro',
  type: 'two-column',
  options: { columnRatios: [0.5, 0.5] },
  content: {
    'pt-br': {
      title: 'Sentence Transformers: embedding de frases para comparar significado',
      body: [
        'No xray do GPT-2, medimos a similaridade de cosseno entre o vetor do token `people` em duas frases diferentes e vimos o valor cair de 1.0 até 0.40 camada a camada. O embedding evolui, mas continua sendo **um vetor por token** — não um vetor para a frase inteira.',
        '',
        'E se quisermos comparar **duas frases** como um todo? Precisamos de um modelo que transforme uma frase inteira em um único vetor, otimizado para essa comparação.',
        '',
        '**Sentence Transformers** (também chamado SBERT) resolve exatamente isso. O modelo é fine-tunado com pares de frases similares e dissimilares: frases parecidas ganham vetores próximos, frases diferentes ganham vetores distantes. O resultado é um embedding por frase que pode ser comparado por **similaridade de cosseno** (dot product com vetores normalizados).',
        '',
        'O snippet usa `intfloat/multilingual-e5-base` — um modelo multilingual que aceita português, inglês e dezenas de outros idiomas. Ele exige um prefixo no texto:',
        '',
        '- `"passage: "` para o documento de referência',
        '- `"query: "` para a pergunta (usado em retrieval)',
        '',
        'O código define uma frase base do direito ("O autor pede indenização por danos morais") e 7 frases de teste com temas variados: jurídico, biologia, hardware, culinária.',
        '',
        'Primeiro calcula a similaridade por dot product bruto. As frases jurídicas aparecem no topo, mas assuntos totalmente irrelevantes (baleia, bolo, RTX) ainda pontuam alto. Por quê? Porque o espaço semântico tem um **viés de posicionamento** — todos os vetores tendem a ficar na mesma região.',
        '',
        'A solução é **centering**: subtraímos a média de todos os vetores e renormalizamos. Isso remove o viés e faz a separação ficar muito mais nítida — frases irrelevantes caem para perto de zero ou negativo, e as relevantes ganham contraste.',
      ].join('\n'),
      rightBody: [
        '```python',
        'snippet:sentence-transformers/sentence-transformers-intro',
        '```',
      ].join('\n'),
      codeExplanations: [
        { lineRange: [1, 4], content: 'Importamos a biblioteca SentenceTransformer e numpy, e carregamos o modelo multilingual e5-base. O download acontece na primeira execução via Hugging Face Hub.' },
        { lineRange: [6, 18], content: 'Definimos uma frase base do direito brasileiro e 7 frases de teste cobrindo temas variados: jurídico (3), biologia, hardware, zoologia e culinária.' },
        { lineRange: [19, 25], content: 'A função `emb()` adiciona o prefixo `"passage: "` exigido pelo e5 para textos de referência e normaliza o embedding para que o dot product seja equivalente à similaridade de cosseno.' },
        { lineRange: [26, 41], content: 'Calculamos o embedding de todas as frases e medimos similaridade por dot product bruto. As frases jurídicas aparecem no topo, mas assuntos totalmente distintos ainda pontuam alto — o espaço semântico tem um viés geral.' },
        { lineRange: [43, 62], content: 'Subtraímos o vetor médio (centro do corpus) de cada embedding e renormalizamos. Isso remove o viés de posicionamento: frases irrelevantes caem para próximo de zero ou negativo, e a separação semântica fica mais nítida.' },
      ],
    },
    'en-us': {
      title: 'Sentence Transformers: embedding sentences to compare meaning',
      body: [
        'In the GPT-2 xray, we measured the cosine similarity of the `people` token vector across two different sentences and saw it drop from 1.0 to 0.40 layer by layer. The embedding evolves, but it stays **one vector per token** — not one vector for the whole sentence.',
        '',
        'What if we want to compare **two sentences** as a whole? We need a model that turns an entire sentence into a single vector, optimized for that comparison.',
        '',
        '**Sentence Transformers** (also called SBERT) does exactly that. The model is fine-tuned on sentence pairs (similar and dissimilar): similar sentences get close vectors, different sentences get distant ones. The result is one embedding per sentence, ready for **cosine similarity** comparison (dot product with normalized vectors).',
        '',
        'The snippet uses `intfloat/multilingual-e5-base` — a multilingual model covering Portuguese, English, and dozens of other languages. It requires a text prefix:',
        '',
        '- `"passage: "` for the reference document',
        '- `"query: "` for the question (used in retrieval)',
        '',
        'The code defines a base legal sentence and 7 test sentences on varied topics: legal, biology, hardware, baking.',
        '',
        'First it computes similarity via raw dot product. Legal sentences rank at the top, but completely irrelevant topics (whale, cake, RTX) still score high. Why? Because the semantic space has a **positioning bias** — all vectors tend to cluster in the same region.',
        '',
        'The fix is **centering**: subtract the mean of all vectors and renormalize. This removes the bias and makes separation much sharper — irrelevant sentences drop to near zero or negative, while relevant ones gain contrast.',
      ].join('\n'),
      rightBody: [
        '```python',
        'snippet:sentence-transformers/sentence-transformers-intro',
        '```',
      ].join('\n'),
      codeExplanations: [
        { lineRange: [1, 4], content: 'We import SentenceTransformer and numpy, and load the multilingual e5-base model. The download happens on first run via the Hugging Face Hub.' },
        { lineRange: [6, 18], content: 'We define a base Brazilian legal sentence and 7 test sentences covering varied topics: legal (3), biology, hardware, zoology, and baking.' },
        { lineRange: [19, 25], content: 'The `emb()` function adds the `"passage: "` prefix required by e5 for reference texts and normalizes the embedding so that dot product equals cosine similarity.' },
        { lineRange: [26, 41], content: 'We compute embeddings for all sentences and measure similarity via raw dot product. Legal sentences rank at the top, but unrelated topics still score relatively high — the semantic space has a global bias.' },
        { lineRange: [43, 62], content: 'We subtract the mean vector (corpus center) from each embedding and renormalize. This removes the positioning bias: irrelevant sentences drop to near zero or negative, making semantic separation sharper.' },
      ],
    },
  },
});
