import { defineSlide } from './_factory';

export const sftLoraMerge = defineSlide({
  id: 'sft-lora-merge',
  type: 'two-column',
  options: { columnRatios: [0.43, 0.57] },
  content: {
    'pt-br': {
      title: 'LoRA: adapter separado ou mergeado',
      body: [
        'Depois do treino, LoRA pode ser usado de duas formas. Você pode manter o adapter separado e carregá-lo sobre a base, ou aplicar `merge_and_unload()` e salvar um modelo com o delta incorporado.',
        '',
        '### Faça merge quando',
        '',
        '- Quer deploy mais simples: um diretório de modelo para carregar',
        '- Vai exportar ou converter o modelo depois',
        '- Não precisa trocar adapters dinamicamente',
        '',
        '### Não faça merge quando',
        '',
        '- Quer comparar vários adapters na mesma base',
        '- Quer manter o checkpoint pequeno',
        '- Quer ligar/desligar comportamentos sem duplicar o modelo base',
        '',
        'Merge não é novo treino. Ele só materializa `W_eff = W0 + B × A` nos pesos salvos.',
      ].join('\n'),
    },
    'en-us': {
      title: 'LoRA: separate or merged adapter',
      body: [
        'After training, LoRA can be used two ways. You can keep the adapter separate and load it on top of the base, or call `merge_and_unload()` and save a model with the delta baked in.',
        '',
        '### Merge when',
        '',
        '- You want simpler deployment: one model directory to load',
        '- You will export or convert the model later',
        '- You do not need to swap adapters dynamically',
        '',
        '### Do not merge when',
        '',
        '- You want to compare multiple adapters on the same base',
        '- You want to keep the checkpoint small',
        '- You want to toggle behaviors without duplicating the base model',
        '',
        'Merge is not new training. It only materializes `W_eff = W0 + B × A` into saved weights.',
      ].join('\n'),
    },
  },
  visual: {
    id: 'code-tabs',
    copy: {
      'pt-br': {
        tabs: [{ label: 'Merge' }],
        codePanels: [
          {
            title: 'Mergear adapter LoRA',
            description: 'Carrega base e adapter, incorpora o delta e salva um modelo pronto para deploy simples.',
            source: { snippetId: 'sft_trl/lora-merge', language: 'python' },
            codeExplanations: [
              { lineRange: [1, 8], content: '`from __future__ import annotations` e imports de sistema, PyTorch, PEFT e Transformers.' },
              { lineRange: [11, 16], content: 'Constantes: modelo base, diretório do adapter LoRA treinado e diretório do modelo mergeado.' },
              { lineRange: [19, 20], content: '`can_use_bf16()`: verifica suporte a BF16 na GPU.' },
              { lineRange: [23, 30], content: '`get_model_dtype()`: seleciona BF16, FP16 ou FP32 com base no hardware disponível.' },
              { lineRange: [33, 41], content: '`main()`: obtém dtype e imprime diagnóstico com modelo base, adapter e caminho de saída.' },
              { lineRange: [43, 45], content: 'Carrega tokenizador do diretório do adapter (herda config do modelo base).' },
              { lineRange: [48, 52], content: 'Carrega modelo base com dtype detectado, device_map condicional e `trust_remote_code`.' },
              { lineRange: [55, 57], content: '`PeftModel.from_pretrained` acopla o adapter LoRA ao modelo base.' },
              { lineRange: [60, 68], content: '`merge_and_unload()` incorpora o delta, cria diretório e salva modelo mergeado com serialização segura.' },
              { lineRange: [71, 73], content: 'Salva tokenizador e exibe caminho final do modelo mergeado.' },
              { lineRange: [76, 77], content: 'Guarda `main()` para execução como script.' },
            ],
          },
        ],
      },
      'en-us': {
        tabs: [{ label: 'Merge' }],
        codePanels: [
          {
            title: 'Merge a LoRA adapter',
            description: 'Loads base and adapter, bakes in the delta, and saves a model for simpler deployment.',
            source: { snippetId: 'sft_trl/lora-merge', language: 'python' },
            codeExplanations: [
              { lineRange: [1, 8], content: '`from __future__ import annotations` and imports for system, PyTorch, PEFT, and Transformers.' },
              { lineRange: [11, 16], content: 'Constants: base model ID, trained LoRA adapter directory, and merged output directory.' },
              { lineRange: [19, 20], content: '`can_use_bf16()`: checks BF16 support on the GPU.' },
              { lineRange: [23, 30], content: '`get_model_dtype()`: selects BF16, FP16, or FP32 based on available hardware.' },
              { lineRange: [33, 41], content: '`main()`: resolves dtype and prints diagnostics showing base model, adapter, and output path.' },
              { lineRange: [43, 45], content: 'Loads tokenizer from the adapter directory (inherits the base model config).' },
              { lineRange: [48, 52], content: 'Loads base model with detected dtype, conditional device_map, and `trust_remote_code`.' },
              { lineRange: [55, 57], content: '`PeftModel.from_pretrained` attaches the LoRA adapter to the base model.' },
              { lineRange: [60, 68], content: '`merge_and_unload()` bakes in the delta, creates the output dir, and saves the merged model with safe serialization.' },
              { lineRange: [71, 73], content: 'Saves tokenizer and prints the final merged model path.' },
              { lineRange: [76, 77], content: 'Standard `main()` guard for script execution.' },
            ],
          },
        ],
      },
    },
  },
});
