import { defineSlide } from './_factory';

export const sftFullFinetuning = defineSlide({
  id: 'sft-full-finetuning',
  type: 'two-column',
  options: { columnRatios: [0.42, 0.58] },
  content: {
    'pt-br': {
      title: 'Full fine-tuning primeiro',
      body: [
        'Full fine-tuning é o SFT direto: todos os pesos treináveis do modelo recebem gradiente e podem mudar.',
        '',
        'É a continuação natural do que vimos no Gutenberg/PyTorch. Lá treinamos continuação de texto; aqui treinamos respostas esperadas em conversas. A loss ainda vem de prever o próximo token correto.',
        '',
        '### O que esse treino faz',
        '',
        '- `Qwen/Qwen3.5-0.8B` expõe `752.393.024` parâmetros treináveis',
        '- O dataset completo do Hub é carregado com splits inteligentes',
        '- `trust_remote_code=True` permite modelos com custom code',
        '- `cosine` scheduler com `warmup_steps=10` suaviza o aprendizado',
        '- `adamw_bnb_8bit` reduz VRAM sem perder qualidade',
        '- O checkpoint salvo é um modelo completo, não um adapter',
      ].join('\n'),
    },
    'en-us': {
      title: 'Full fine-tuning first',
      body: [
        'Full fine-tuning is direct SFT: every trainable model weight receives gradients and can change.',
        '',
        'It is the natural continuation of the Gutenberg/PyTorch block. There we trained text continuation; here we train expected answers in conversations. The loss still comes from predicting the correct next token.',
        '',
        '### What this training does',
        '',
        '- `Qwen/Qwen3.5-0.8B` exposes `752,393,024` trainable parameters',
        '- The full Hub dataset is loaded with intelligent splits',
        '- `trust_remote_code=True` allows models with custom code',
        '- `cosine` scheduler with `warmup_steps=10` smooths learning',
        '- `adamw_bnb_8bit` reduces VRAM without losing quality',
        '- The saved checkpoint is a full model, not an adapter',
      ].join('\n'),
    },
  },
  visual: {
    id: 'code-tabs',
    copy: {
      'pt-br': {
        tabs: [{ label: 'Ambiente' }, { label: 'Full SFT' }],
        codePanels: [
          {
            title: 'Checar versões e GPU',
            description: 'Confirma TRL/Transformers/PEFT atualizados antes de treinar.',
            source: { snippetId: 'sft_trl/environment-check', language: 'python' },
            codeExplanations: [
              { lineRange: [1, 3], content: 'Importamos metadados dos pacotes e PyTorch.' },
              { lineRange: [5, 8], content: 'Listamos as versões para evitar rodar com uma API antiga.' },
              { lineRange: [10, 13], content: 'Checamos CUDA, nome da GPU e VRAM disponível.' },
            ],
          },
          {
            title: 'Treino full com TRL',
            description: 'Executa SFT sem PEFT: todos os pesos do Qwen participam do update.',
            source: { snippetId: 'sft_trl/full-finetuning-train', language: 'python' },
            codeExplanations: [
              { lineRange: [1, 9], content: 'Importamos sistema, PyTorch, dataset, Transformers e TRL.' },
              { lineRange: [11, 15], content: 'Fixamos modelo, dataset, saída e seed. `SFT_OUTPUT_ROOT` permite usar outro disco; o padrão é `runs/`.' },
              { lineRange: [18, 33], content: 'Função principal: seed, TF32, carregamento do dataset com splits inteligentes (validation/test/train_test_split).' },
              { lineRange: [35, 38], content: 'Tokenizer com `trust_remote_code=True`, pad_token igual a eos_token e padding à direita.' },
              { lineRange: [40, 46], content: 'Modelo em bfloat16 ou float32 conforme GPU, com cache desativado e gradient checkpointing habilitado.' },
              { lineRange: [48, 49], content: '`SFTConfig` e `output_dir`: abre a config e define onde salvar o checkpoint.' },
              { lineRange: [50, 50], content: '`num_train_epochs=3`: 3 épocas completas sobre o dataset.' },
              { lineRange: [51, 51], content: '`max_steps=-1`: sem limite de steps; treina até acabar as épocas.' },
              { lineRange: [52, 53], content: '`per_device_train/eval_batch_size=16`: 16 amostras por GPU no treino e validação.' },
              { lineRange: [54, 54], content: '`auto_find_batch_size=True`: tenta 16, reduz automaticamente se faltar VRAM.' },
              { lineRange: [55, 55], content: '`gradient_accumulation_steps=1`: sem acumulação de gradiente.' },
              { lineRange: [56, 56], content: '`learning_rate=1.5e-5`: taxa de aprendizado inicial.' },
              { lineRange: [57, 57], content: '`warmup_steps=10`: aquecimento linear nos primeiros 10 steps.' },
              { lineRange: [58, 58], content: '`weight_decay=0.01`: regularização L2 para evitar overfitting.' },
              { lineRange: [59, 59], content: '`lr_scheduler_type="cosine"`: decaimento cosine do learning rate.' },
              { lineRange: [60, 60], content: '`optim="adamw_bnb_8bit"`: AdamW em 8-bit para reduzir VRAM.' },
              { lineRange: [61, 61], content: '`max_length=1024`: comprimento máximo de sequência para tokenização.' },
              { lineRange: [62, 63], content: '`bf16`/`fp16`: precisão de treinamento conforme suporte da GPU.' },
              { lineRange: [64, 64], content: '`gradient_checkpointing=True`: recalcula ativações para economizar VRAM.' },
              { lineRange: [65, 66], content: '`assistant_only_loss=True` e `loss_type="nll"`: loss apenas nos tokens do assistente, usando NLL.' },
              { lineRange: [67, 68], content: '`do_train` e `do_eval=True`: habilita loops de treino e validação.' },
              { lineRange: [69, 71], content: 'Eval e logging: avalia e loga a cada 50 steps.' },
              { lineRange: [72, 74], content: 'Salvamento: checkpoint a cada 50 steps, mantém 2 mais recentes.' },
              { lineRange: [75, 77], content: 'Melhor modelo: recarrega o checkpoint com menor eval_loss ao final.' },
              { lineRange: [78, 79], content: '`report_to="none"` e `remove_unused_columns`: desliga TensorBoard, mantém colunas.' },
              { lineRange: [80, 81], content: '`seed` e `data_seed`: sementes de reprodutibilidade para treino e dados.' },
              { lineRange: [82, 84], content: '`tf32=True` e `use_cache=False`: TF32 para matmul mais rápido e cache desativado.' },
              { lineRange: [86, 92], content: '`SFTTrainer` recebe treino e validação; não há PEFT aqui, então todos os pesos treináveis entram no update.' },
              { lineRange: [94, 108], content: 'Auditamos parâmetros treináveis, linhas de treino/eval, executamos o treino e salvamos o checkpoint completo.' },
            ],
          },
        ],
      },
      'en-us': {
        tabs: [{ label: 'Environment' }, { label: 'Full SFT' }],
        codePanels: [
          {
            title: 'Check versions and GPU',
            description: 'Confirms TRL/Transformers/PEFT are updated before training.',
            source: { snippetId: 'sft_trl/environment-check', language: 'python' },
            codeExplanations: [
              { lineRange: [1, 3], content: 'We import package metadata and PyTorch.' },
              { lineRange: [5, 8], content: 'We list versions to avoid running against an old API.' },
              { lineRange: [10, 13], content: 'We check CUDA, GPU name, and available VRAM.' },
            ],
          },
          {
            title: 'Full training with TRL',
            description: 'Runs SFT without PEFT: every Qwen weight participates in the update.',
            source: { snippetId: 'sft_trl/full-finetuning-train', language: 'python' },
            codeExplanations: [
              { lineRange: [1, 9], content: 'We import system helpers, PyTorch, datasets, Transformers, and TRL.' },
              { lineRange: [11, 15], content: 'We pin model, dataset, output, and seed. `SFT_OUTPUT_ROOT` can point to another drive; default is `runs/`.' },
              { lineRange: [18, 33], content: 'Main function: seed, TF32, dataset loading with intelligent splits (validation/test/train_test_split).' },
              { lineRange: [35, 38], content: 'Tokenizer with `trust_remote_code=True`, pad_token equal to eos_token, and right-side padding.' },
              { lineRange: [40, 46], content: 'Model in bfloat16 or float32 depending on GPU, with cache disabled and gradient checkpointing enabled.' },
              { lineRange: [48, 49], content: '`SFTConfig` and `output_dir`: opens the config and sets where to save the checkpoint.' },
              { lineRange: [50, 50], content: '`num_train_epochs=3`: 3 complete passes over the dataset.' },
              { lineRange: [51, 51], content: '`max_steps=-1`: no step limit; trains until epochs are exhausted.' },
              { lineRange: [52, 53], content: '`per_device_train/eval_batch_size=16`: 16 samples per GPU for training and evaluation.' },
              { lineRange: [54, 54], content: '`auto_find_batch_size=True`: tries 16, reduces automatically if VRAM runs out.' },
              { lineRange: [55, 55], content: '`gradient_accumulation_steps=1`: no gradient accumulation.' },
              { lineRange: [56, 56], content: '`learning_rate=1.5e-5`: initial learning rate.' },
              { lineRange: [57, 57], content: '`warmup_steps=10`: linear warmup for the first 10 steps.' },
              { lineRange: [58, 58], content: '`weight_decay=0.01`: L2 regularization to prevent overfitting.' },
              { lineRange: [59, 59], content: '`lr_scheduler_type="cosine"`: cosine decay for the learning rate.' },
              { lineRange: [60, 60], content: '`optim="adamw_bnb_8bit"`: 8-bit AdamW to reduce VRAM usage.' },
              { lineRange: [61, 61], content: '`max_length=1024`: maximum sequence length for tokenization.' },
              { lineRange: [62, 63], content: '`bf16`/`fp16`: training precision depending on GPU support.' },
              { lineRange: [64, 64], content: '`gradient_checkpointing=True`: recomputes activations to save VRAM.' },
              { lineRange: [65, 66], content: '`assistant_only_loss=True` and `loss_type="nll"`: loss computed only on assistant tokens using NLL.' },
              { lineRange: [67, 68], content: '`do_train` and `do_eval=True`: enables training and evaluation loops.' },
              { lineRange: [69, 71], content: 'Eval and logging: evaluates and logs every 50 steps.' },
              { lineRange: [72, 74], content: 'Saving: checkpoint every 50 steps, keeps only 2 most recent.' },
              { lineRange: [75, 77], content: 'Best model: reloads the checkpoint with lowest eval_loss at the end.' },
              { lineRange: [78, 79], content: '`report_to="none"` and `remove_unused_columns`: disables TensorBoard, keeps dataset columns.' },
              { lineRange: [80, 81], content: '`seed` and `data_seed`: reproducibility seeds for training and data.' },
              { lineRange: [82, 84], content: '`tf32=True` and `use_cache=False`: TF32 for faster matmul, cache disabled during training.' },
              { lineRange: [86, 92], content: '`SFTTrainer` receives train and eval data; no PEFT here, so all trainable weights participate.' },
              { lineRange: [94, 108], content: 'We audit trainable parameters, train/eval rows, run training, and save the full checkpoint.' },
            ],
          },
        ],
      },
    },
  },
});
