import { defineSlide } from './_factory';

export const sftFullConfig = defineSlide({
  id: 'sft-full-config',
  type: 'two-column',
  options: { columnRatios: [0.5, 0.5] },
  content: {
    'pt-br': {
      title: 'SFTConfig sem caixa-preta',
      body: [
        '`SFTConfig` é onde o treino deixa de ser "mágica da TRL" e vira configuração explícita do loop.',
        '',
        '### Output e controles gerais',
        '',
        '- `output_dir`: onde salvar checkpoints e logs',
        '- `do_train=True`: habilita o loop de treino',
        '- `max_steps=-1`: usa `num_train_epochs` ao invés de limite fixo de steps',
        '',
        '### Tamanho do treino',
        '',
        '- `num_train_epochs=3`: quantas passagens completas no dataset',
        '- `per_device_train_batch_size=16`: exemplos por GPU antes da acumulação',
        '- `per_device_eval_batch_size=16`: exemplos por GPU na validação',
        '- `gradient_accumulation_steps=1`: soma gradientes antes do update (1 = update a cada batch)',
        '- `max_length=1024`: limite de tokens por conversa renderizada',
        '',
        '### Qualidade do update',
        '',
        '- `learning_rate=1.5e-5`: tamanho do passo nos pesos',
        '- `warmup_steps=10`:LR linear nos primeiros 10 steps antes do cosine',
        '- `weight_decay=0.01`: regularização L2 para evitar overfitting',
        '- `lr_scheduler_type="cosine"`: decai LR em curva suave após warmup',
        '- `optim="adamw_bnb_8bit"`: otimizador 8-bit que reduz VRAM ~75%',
      ].join('\n'),
      rightBody: [
        '### Precisão e eficiência',
        '',
        '- `bf16`: bfloat16 se GPU suporta (melhor estabilidade)',
        '- `fp16`: float16 como fallback se bf16 não disponível',
        '- `gradient_checkpointing=True`: troca compute por menos VRAM',
        '- `assistant_only_loss=True`: calcula loss só no assistente, ignora prompt',
        '- `tf32=True`: acelera matmul em GPUs Ampere+',
        '- `use_cache=False`: desativa KV cache para compatibilidade com gradient checkpointing',
        '',
        '### Avaliação e checkpoints',
        '',
        '- `do_eval=True`: habilita avaliação durante o treino',
        '- `eval_strategy="steps"`: avalia por intervalo de steps',
        '- `eval_steps=50`: valida a cada 50 updates',
        '- `save_strategy="steps"`: salva por intervalo de steps',
        '- `save_steps=50`: checkpoint a cada 50 updates',
        '- `save_total_limit=2`: mantém apenas os 2 checkpoints mais recentes',
        '- `load_best_model_at_end=True`: retoma melhor modelo ao final',
        '- `metric_for_best_model="eval_loss"`: métrica para definir "melhor"',
        '- `greater_is_better=False`: menor loss = melhor modelo',
        '',
        '### Observabilidade e reprodutibilidade',
        '',
        '- `logging_steps=1`: log a cada update',
        '- `report_to="tensorboard"`: salva métricas para visualização',
        '- `remove_unused_columns=False`: preserva `messages` para o pipeline',
        '- `seed=42` e `data_seed=42`: garante reprodutibilidade no treino e no split',
      ].join('\n'),
    },
    'en-us': {
      title: 'SFTConfig without black box',
      body: [
        '`SFTConfig` is where training stops looking like "TRL magic" and becomes an explicit loop configuration.',
        '',
        '### Output and general controls',
        '',
        '- `output_dir`: where to save checkpoints and logs',
        '- `do_train=True`: enables the training loop',
        '- `max_steps=-1`: uses `num_train_epochs` instead of a fixed step limit',
        '',
        '### Training size',
        '',
        '- `num_train_epochs=3`: how many full passes over the dataset',
        '- `per_device_train_batch_size=16`: examples per GPU before accumulation',
        '- `per_device_eval_batch_size=16`: examples per GPU during validation',
        '- `gradient_accumulation_steps=1`: accumulate gradients before one update (1 = update every batch)',
        '- `max_length=1024`: token limit per rendered conversation',
        '',
        '### Update quality',
        '',
        '- `learning_rate=1.5e-5`: step size applied to weights',
        '- `warmup_steps=10`: linear LR warmup for 10 steps before cosine',
        '- `weight_decay=0.01`: L2 regularization to prevent overfitting',
        '- `lr_scheduler_type="cosine"`: decays LR in a smooth curve after warmup',
        '- `optim="adamw_bnb_8bit"`: 8-bit optimizer that cuts VRAM ~75%',
      ].join('\n'),
      rightBody: [
        '### Precision and efficiency',
        '',
        '- `bf16`: bfloat16 if GPU supports it (better stability)',
        '- `fp16`: float16 as fallback when bf16 is unavailable',
        '- `gradient_checkpointing=True`: trades compute for lower VRAM',
        '- `assistant_only_loss=True`: computes loss only on assistant, ignores prompt',
        '- `tf32=True`: accelerates matmul on Ampere+ GPUs',
        '- `use_cache=False`: disables KV cache for gradient checkpointing compatibility',
        '',
        '### Evaluation and checkpoints',
        '',
        '- `do_eval=True`: enables evaluation during training',
        '- `eval_strategy="steps"`: evaluates by step interval',
        '- `eval_steps=50`: validates every 50 updates',
        '- `save_strategy="steps"`: saves by step interval',
        '- `save_steps=50`: checkpoint every 50 updates',
        '- `save_total_limit=2`: keeps only the 2 most recent checkpoints',
        '- `load_best_model_at_end=True`: resumes best model at the end',
        '- `metric_for_best_model="eval_loss"`: metric to define "best"',
        '- `greater_is_better=False`: lower loss = better model',
        '',
        '### Observability and reproducibility',
        '',
        '- `logging_steps=1`: log every update',
        '- `report_to="tensorboard"`: saves metrics for visualization',
        '- `remove_unused_columns=False`: preserves `messages` for the pipeline',
        '- `seed=42` and `data_seed=42`: ensures reproducibility in training and splits',
      ].join('\n'),
    },
  },
});
