import { defineSlide } from './_factory';

export const sftTrlTrain = defineSlide({
  id: 'sft-trl-train',
  type: 'two-column',
  options: { columnRatios: [0.43, 0.57] },
  content: {
    'pt-br': {
      title: 'TRL: LoRA prática com SFTTrainer',
      body: [
        '`SFTTrainer` é o `Trainer` especializado da TRL para SFT conversacional. Ele não substitui PyTorch: organiza `forward`, loss, `backward()` e optimizer step para datasets de chat.',
        '',
        '### O contrato do exemplo',
        '',
        '- Dataset do Hub: `celsowm/valdoria-sft-qwen35-dataset`',
        '- O campo necessário é `messages`',
        '- `select(range(...))` é só o corte didático de smoke test',
        '- Para treinar tudo, remova o `.select(...)`',
        '- `train_test_split` separa uma validação pequena para acompanhar a loss',
        '- No teste real, 220 steps LoRA chegaram a loss média `0.6122` e eval loss `0.2924`',
        '',
        'A diferença para o full não é a tarefa. É o conjunto de pesos que responde à loss: aqui a base fica congelada e só o adapter aprende.',
      ].join('\n'),
    },
    'en-us': {
      title: 'TRL: practical LoRA with SFTTrainer',
      body: [
        '`SFTTrainer` is TRL specialized `Trainer` for conversational SFT. It does not replace PyTorch: it organizes `forward`, loss, `backward()`, and optimizer step for chat datasets.',
        '',
        '### Example contract',
        '',
        '- Hub dataset: `celsowm/valdoria-sft-qwen35-dataset`',
        '- The required field is `messages`',
        '- `select(range(...))` is only the teaching smoke-test cut',
        '- To train on everything, remove `.select(...)`',
        '- `train_test_split` creates a small validation set to watch loss',
        '- In the real test, 220 LoRA steps reached average loss `0.6122` and eval loss `0.2924`',
        '',
        'The difference from full training is not the task. It is the set of weights that responds to loss: here the base is frozen and only the adapter learns.',
      ].join('\n'),
    },
  },
  visual: {
    id: 'code-tabs',
    copy: {
      'pt-br': {
        tabs: [{ label: 'LoRA' }],
        codePanels: [
          {
            title: 'Treinar adapter LoRA com TRL',
            description: 'Roda SFT em Valdoria, avalia durante o smoke e salva apenas o adapter.',
            source: { snippetId: 'sft_trl/lora-train', language: 'python' },
            codeExplanations: [
              { lineRange: [1, 10], content: '`from __future__ import annotations` e imports de sistema, PyTorch, datasets, PEFT, Transformers e TRL.' },
              { lineRange: [13, 19], content: 'Constantes: modelo, dataset, seed e caminhos de saída. `SFT_OUTPUT_ROOT` permite salvar em outro disco.' },
              { lineRange: [22, 27], content: '`can_use_tf32()`: detecta GPU Ampere+ para TF32.' },
              { lineRange: [30, 31], content: '`can_use_bf16()`: verifica suporte a BF16 na GPU.' },
              { lineRange: [34, 41], content: '`get_model_dtype()`: seleciona BF16, FP16 ou FP32 conforme hardware.' },
              { lineRange: [44, 48], content: '`get_optim()`: escolhe `adamw_bnb_8bit` (GPU) ou `adamw_torch` (CPU).' },
              { lineRange: [51, 62], content: '`print_cuda_info()`: exibe diagnóstico de GPU no início do treino para auditoria de hardware.' },
              { lineRange: [65, 66], content: '`load_train_eval_dataset()`: carrega dataset do Hub.' },
              { lineRange: [73, 82], content: 'Corta 1024 exemplos para smoke test, aplica `train_test_split` 90/10 e retorna splits.' },
              { lineRange: [85, 89], content: '`main()`: cria diretório de saída e fixa a semente para reprodutibilidade.' },
              { lineRange: [91, 104], content: 'Detecta BF16, TF32, dtype e otimizador; ativa TF32 se suportado; exibe diagnóstico de hardware.' },
              { lineRange: [106, 110], content: 'Carrega os datasets de treino e avaliação com smoke configurado.' },
              { lineRange: [113, 116], content: 'Carrega tokenizer com `trust_remote_code` e configura padding como EOS no lado direito.' },
              { lineRange: [118, 120], content: 'Monta `model_kwargs` com dtype e `trust_remote_code`.' },
              { lineRange: [123, 124], content: 'Adiciona `device_map="auto"` condicional se GPU disponível.' },
              { lineRange: [126, 128], content: 'Carrega modelo base com os kwargs montados.' },
              { lineRange: [131, 146], content: 'Desabilita cache do modelo e configura `LoraConfig` com rank 32, alpha 64, dropout 0.03, mirando atenção e MLP.' },
              { lineRange: [150, 151], content: 'Inicia `SFTConfig` com diretório de saída.' },
              { lineRange: [154, 170], content: 'Configura steps, batch, LR, packing e precisão condicional (BF16/FP16/TF32).' },
              { lineRange: [173, 179], content: 'Ativa gradient checkpointing, loss NLL com supervisão apenas do assistente.' },
              { lineRange: [182, 185], content: 'Ativa avaliação a cada 20 steps com logging síncrono.' },
              { lineRange: [188, 195], content: 'Desativa salvamento automático e relatórios; define seed e data_seed.' },
              { lineRange: [198, 204], content: '`SFTTrainer` recebe modelo, SFTConfig, datasets, tokenizer e config PEFT.' },
              { lineRange: [207, 216], content: 'Calcula e exibe contagem de parâmetros treináveis e totais antes do treino.' },
              { lineRange: [218, 228], content: 'Treina o modelo, exibe métricas finais, salva adapter LoRA e tokenizer no diretório de saída.' },
              { lineRange: [231, 232], content: 'Guarda `main()` para execução como script.' },
            ],
          },
        ],
      },
      'en-us': {
        tabs: [{ label: 'LoRA' }],
        codePanels: [
          {
            title: 'Train a LoRA adapter with TRL',
            description: 'Runs SFT on Valdoria, evaluates during the smoke, and saves only the adapter.',
            source: { snippetId: 'sft_trl/lora-train', language: 'python' },
            codeExplanations: [
              { lineRange: [1, 10], content: '`from __future__ import annotations` and imports for system, PyTorch, datasets, PEFT, Transformers, and TRL.' },
              { lineRange: [13, 19], content: 'Constants: model, dataset, seed, and output paths. `SFT_OUTPUT_ROOT` can save to another drive.' },
              { lineRange: [22, 27], content: '`can_use_tf32()`: detects Ampere+ GPU for TF32 support.' },
              { lineRange: [30, 31], content: '`can_use_bf16()`: checks BF16 support on the GPU.' },
              { lineRange: [34, 41], content: '`get_model_dtype()`: selects BF16, FP16, or FP32 based on hardware.' },
              { lineRange: [44, 48], content: '`get_optim()`: picks `adamw_bnb_8bit` (GPU) or `adamw_torch` (CPU).' },
              { lineRange: [51, 62], content: '`print_cuda_info()`: prints GPU diagnostics at training start for hardware audit.' },
              { lineRange: [65, 66], content: '`load_train_eval_dataset()`: loads the dataset from the Hub.' },
              { lineRange: [73, 82], content: 'Takes 1024 smoke-test examples, applies 90/10 `train_test_split`, and returns splits.' },
              { lineRange: [85, 89], content: '`main()`: creates output directory and fixes the seed for reproducibility.' },
              { lineRange: [91, 104], content: 'Detects BF16, TF32, dtype, and optimizer; enables TF32 if supported; prints hardware diagnostics.' },
              { lineRange: [106, 110], content: 'Loads train and eval datasets with the smoke configuration.' },
              { lineRange: [113, 116], content: 'Loads tokenizer with `trust_remote_code` and sets padding to EOS on the right side.' },
              { lineRange: [118, 120], content: 'Builds `model_kwargs` with dtype and `trust_remote_code`.' },
              { lineRange: [123, 124], content: 'Adds conditional `device_map="auto"` if GPU is available.' },
              { lineRange: [126, 128], content: 'Loads the base model with the assembled kwargs.' },
              { lineRange: [131, 146], content: 'Disables model cache and configures `LoraConfig` with rank 32, alpha 64, dropout 0.03, targeting attention and MLP.' },
              { lineRange: [150, 151], content: 'Starts `SFTConfig` with the output directory.' },
              { lineRange: [154, 170], content: 'Configures steps, batch, LR, packing, and conditional precision (BF16/FP16/TF32).' },
              { lineRange: [173, 179], content: 'Enables gradient checkpointing, NLL loss with assistant-only supervision.' },
              { lineRange: [182, 185], content: 'Enables evaluation every 20 steps with synchronous logging.' },
              { lineRange: [188, 195], content: 'Disables auto-saving and reporting; sets seed and data_seed.' },
              { lineRange: [198, 204], content: '`SFTTrainer` receives model, SFTConfig, datasets, tokenizer, and PEFT config.' },
              { lineRange: [207, 216], content: 'Calculates and prints trainable and total parameter counts before training.' },
              { lineRange: [218, 228], content: 'Trains the model, prints final metrics, saves LoRA adapter and tokenizer to the output directory.' },
              { lineRange: [231, 232], content: 'Standard `main()` guard for script execution.' },
            ],
          },
        ],
      },
    },
  },
});
