import { defineSlide } from './_factory';

export const sftLoraMerge = defineSlide({
  id: 'sft-lora-merge',
  type: 'two-column',
  options: { columnRatios: [0.43, 0.57] },
  content: {
    'pt-br': {
      title: 'LoRA: adapter separado ou mergeado',
      body: [
        'Depois do treino, LoRA pode ser usado de duas formas. Você pode manter o adapter separado e carregá-lo sobre a base, ou aplicar `merge_and_unload()` e salvar um modelo com o delta incorporado.',
        '',
        '### Faça merge quando',
        '',
        '- Quer deploy mais simples: um diretório de modelo para carregar',
        '- Vai exportar ou converter o modelo depois',
        '- Não precisa trocar adapters dinamicamente',
        '',
        '### Não faça merge quando',
        '',
        '- Quer comparar vários adapters na mesma base',
        '- Quer manter o checkpoint pequeno',
        '- Quer ligar/desligar comportamentos sem duplicar o modelo base',
        '',
        'Merge não é novo treino. Ele só materializa `W_eff = W0 + B × A` nos pesos salvos.',
      ].join('\n'),
    },
    'en-us': {
      title: 'LoRA: separate or merged adapter',
      body: [
        'After training, LoRA can be used two ways. You can keep the adapter separate and load it on top of the base, or call `merge_and_unload()` and save a model with the delta baked in.',
        '',
        '### Merge when',
        '',
        '- You want simpler deployment: one model directory to load',
        '- You will export or convert the model later',
        '- You do not need to swap adapters dynamically',
        '',
        '### Do not merge when',
        '',
        '- You want to compare multiple adapters on the same base',
        '- You want to keep the checkpoint small',
        '- You want to toggle behaviors without duplicating the base model',
        '',
        'Merge is not new training. It only materializes `W_eff = W0 + B × A` into saved weights.',
      ].join('\n'),
    },
  },
  visual: {
    id: 'code-tabs',
    copy: {
      'pt-br': {
        tabs: [
          { label: 'Inferência (adapter)' },
          { label: 'Merge' },
          { label: 'Inferência (merged)' },
        ],
        codePanels: [
          {
            title: 'Inferência com adapter separado',
            description: 'Carrega modelo base e acopla o adapter LoRA via PeftModel — sem merge, sem duplicar pesos.',
            source: { snippetId: 'sft_trl/lora-inference-adapter', language: 'python' },
            codeExplanations: [
              { lineRange: [1, 8], content: 'Imports: sem `PeftModel` não há LoRA; aqui ele é necessário para acoplar o adapter.' },
              { lineRange: [11, 14], content: 'Constantes: modelo base e caminho do adapter LoRA treinado.' },
              { lineRange: [17, 20], content: '`get_model_dtype()`: BF16 se suportado, FP16 se só CUDA, FP32 em CPU.' },
              { lineRange: [23, 27], content: '`main()`: resolve dtype e exibe caminho do adapter.' },
              { lineRange: [29, 32], content: 'Tokenizer carregado do diretório do adapter (herda config do modelo base).' },
              { lineRange: [34, 39], content: 'Modelo base carregado com dtype e `device_map` — pesos originais, sem nenhuma modificação.' },
              { lineRange: [41, 43], content: '`PeftModel.from_pretrained` injeta o adapter LoRA sobre o base. Pesos do adapter somam em cima durante o forward.' },
              { lineRange: [45, 51], content: 'Monta prompt no formato chat e aplica o template do tokenizer com `add_generation_prompt=True`.' },
              { lineRange: [53, 54], content: 'Move input para GPU se disponível.' },
              { lineRange: [56, 63], content: '`torch.no_grad()` + `model.generate()`: sampling com temperatura 0.7 e top-p 0.9.' },
              { lineRange: [65, 66], content: 'Fatia apenas os tokens gerados (descarta o prompt) e decodifica.' },
              { lineRange: [69, 70], content: 'Guard `__main__`.' },
            ],
          },
          {
            title: 'Mergear adapter LoRA',
            description: 'Carrega base e adapter, incorpora o delta e salva um modelo pronto para deploy simples.',
            source: { snippetId: 'sft_trl/lora-merge', language: 'python' },
            codeExplanations: [
              { lineRange: [1, 8], content: '`from __future__ import annotations` e imports de sistema, PyTorch, PEFT e Transformers.' },
              { lineRange: [11, 16], content: 'Constantes: modelo base, diretório do adapter LoRA treinado e diretório do modelo mergeado.' },
              { lineRange: [19, 20], content: '`can_use_bf16()`: verifica suporte a BF16 na GPU.' },
              { lineRange: [23, 30], content: '`get_model_dtype()`: seleciona BF16, FP16 ou FP32 com base no hardware disponível.' },
              { lineRange: [33, 41], content: '`main()`: obtém dtype e imprime diagnóstico com modelo base, adapter e caminho de saída.' },
              { lineRange: [43, 45], content: 'Carrega tokenizador do diretório do adapter (herda config do modelo base).' },
              { lineRange: [48, 52], content: 'Carrega modelo base com dtype detectado, device_map condicional e `trust_remote_code`.' },
              { lineRange: [55, 57], content: '`PeftModel.from_pretrained` acopla o adapter LoRA ao modelo base.' },
              { lineRange: [60, 68], content: '`merge_and_unload()` incorpora o delta, cria diretório e salva modelo mergeado com serialização segura.' },
              { lineRange: [71, 73], content: 'Salva tokenizador e exibe caminho final do modelo mergeado.' },
              { lineRange: [76, 77], content: 'Guarda `main()` para execução como script.' },
            ],
          },
          {
            title: 'Inferência com modelo mergeado',
            description: 'Carrega o modelo mergeado como um AutoModelForCausalLM normal — sem PeftModel, sem adapter separado.',
            source: { snippetId: 'sft_trl/lora-inference-merged', language: 'python' },
            codeExplanations: [
              { lineRange: [1, 7], content: 'Imports: note que `peft` não aparece — o modelo mergeado não precisa de nenhuma classe PEFT.' },
              { lineRange: [10, 11], content: 'Constante: caminho do modelo mergeado (saída do script de merge).' },
              { lineRange: [14, 17], content: '`get_model_dtype()`: mesma lógica de detecção de BF16/FP16/FP32.' },
              { lineRange: [20, 24], content: '`main()`: resolve dtype e exibe caminho do modelo.' },
              { lineRange: [26, 29], content: 'Tokenizer carregado do diretório mergeado — inclui os arquivos do tokenizer salvos pelo script de merge.' },
              { lineRange: [31, 38], content: '`AutoModelForCausalLM.from_pretrained(MERGED_DIR)` — carrega o modelo como se fosse qualquer outro. Sem PeftModel, sem adapter.' },
              { lineRange: [40, 46], content: 'Mesmo pipeline de inferência: chat template + `apply_chat_template` com `add_generation_prompt=True`.' },
              { lineRange: [48, 49], content: 'Move input para GPU se disponível.' },
              { lineRange: [51, 58], content: '`torch.no_grad()` + `model.generate()` — idêntico ao script de adapter, mas agora o modelo já tem o delta incorporado nos pesos.' },
              { lineRange: [60, 61], content: 'Fatia tokens gerados e decodifica.' },
              { lineRange: [64, 65], content: 'Guard `__main__`.' },
            ],
          },
        ],
      },
      'en-us': {
        tabs: [
          { label: 'Inference (adapter)' },
          { label: 'Merge' },
          { label: 'Inference (merged)' },
        ],
        codePanels: [
          {
            title: 'Inference with separate adapter',
            description: 'Loads the base model and attaches the LoRA adapter via PeftModel — no merge, no weight duplication.',
            source: { snippetId: 'sft_trl/lora-inference-adapter', language: 'python' },
            codeExplanations: [
              { lineRange: [1, 8], content: 'Imports: without `PeftModel` there is no LoRA; here it is required to attach the adapter.' },
              { lineRange: [11, 14], content: 'Constants: base model ID and path to the trained LoRA adapter.' },
              { lineRange: [17, 20], content: '`get_model_dtype()`: BF16 if supported, FP16 if CUDA only, FP32 on CPU.' },
              { lineRange: [23, 27], content: '`main()`: resolves dtype and prints the adapter path.' },
              { lineRange: [29, 32], content: 'Tokenizer loaded from the adapter directory (inherits the base model config).' },
              { lineRange: [34, 39], content: 'Base model loaded with dtype and conditional `device_map` — original weights, no modification.' },
              { lineRange: [41, 43], content: '`PeftModel.from_pretrained` injects the LoRA adapter on top of the base. Adapter weights are added during the forward pass.' },
              { lineRange: [45, 51], content: 'Builds the chat prompt and applies the tokenizer template with `add_generation_prompt=True`.' },
              { lineRange: [53, 54], content: 'Moves input to GPU if available.' },
              { lineRange: [56, 63], content: '`torch.no_grad()` + `model.generate()`: sampling with temperature 0.7 and top-p 0.9.' },
              { lineRange: [65, 66], content: 'Slices only the generated tokens (discards the prompt) and decodes.' },
              { lineRange: [69, 70], content: '`__main__` guard.' },
            ],
          },
          {
            title: 'Merge a LoRA adapter',
            description: 'Loads base and adapter, bakes in the delta, and saves a model for simpler deployment.',
            source: { snippetId: 'sft_trl/lora-merge', language: 'python' },
            codeExplanations: [
              { lineRange: [1, 8], content: '`from __future__ import annotations` and imports for system, PyTorch, PEFT, and Transformers.' },
              { lineRange: [11, 16], content: 'Constants: base model ID, trained LoRA adapter directory, and merged output directory.' },
              { lineRange: [19, 20], content: '`can_use_bf16()`: checks BF16 support on the GPU.' },
              { lineRange: [23, 30], content: '`get_model_dtype()`: selects BF16, FP16, or FP32 based on available hardware.' },
              { lineRange: [33, 41], content: '`main()`: resolves dtype and prints diagnostics showing base model, adapter, and output path.' },
              { lineRange: [43, 45], content: 'Loads tokenizer from the adapter directory (inherits the base model config).' },
              { lineRange: [48, 52], content: 'Loads base model with detected dtype, conditional device_map, and `trust_remote_code`.' },
              { lineRange: [55, 57], content: '`PeftModel.from_pretrained` attaches the LoRA adapter to the base model.' },
              { lineRange: [60, 68], content: '`merge_and_unload()` bakes in the delta, creates the output dir, and saves the merged model with safe serialization.' },
              { lineRange: [71, 73], content: 'Saves tokenizer and prints the final merged model path.' },
              { lineRange: [76, 77], content: 'Standard `main()` guard for script execution.' },
            ],
          },
          {
            title: 'Inference with merged model',
            description: 'Loads the merged model as a plain AutoModelForCausalLM — no PeftModel, no separate adapter.',
            source: { snippetId: 'sft_trl/lora-inference-merged', language: 'python' },
            codeExplanations: [
              { lineRange: [1, 7], content: 'Imports: note that `peft` is absent — the merged model needs no PEFT class at all.' },
              { lineRange: [10, 11], content: 'Constant: path to the merged model (output of the merge script).' },
              { lineRange: [14, 17], content: '`get_model_dtype()`: same BF16/FP16/FP32 detection logic.' },
              { lineRange: [20, 24], content: '`main()`: resolves dtype and prints the model path.' },
              { lineRange: [26, 29], content: 'Tokenizer loaded from the merged directory — includes the tokenizer files saved by the merge script.' },
              { lineRange: [31, 38], content: '`AutoModelForCausalLM.from_pretrained(MERGED_DIR)` — loads the model like any other. No PeftModel, no adapter.' },
              { lineRange: [40, 46], content: 'Same inference pipeline: chat template + `apply_chat_template` with `add_generation_prompt=True`.' },
              { lineRange: [48, 49], content: 'Moves input to GPU if available.' },
              { lineRange: [51, 58], content: '`torch.no_grad()` + `model.generate()` — identical to the adapter script, but the model already has the delta baked into its weights.' },
              { lineRange: [60, 61], content: 'Slices generated tokens and decodes.' },
              { lineRange: [64, 65], content: '`__main__` guard.' },
            ],
          },
        ],
      },
    },
  },
});
