import { defineSlide } from './_factory';

export const sftMetrics = defineSlide({
  id: 'sft-metrics',
  type: 'two-column',
  options: { columnRatios: [0.45, 0.55] },
  content: {
    'pt-br': {
      title: 'Métricas do SFT',
      body: [
        'Durante o treino, o `SFTTrainer` produz 3 blocos de métricas que você precisa saber interpretar.',
        '',
        '### 1. Métricas de treino (a cada `logging_steps=50`)',
        '',
        '```',
        "{'loss': 2.314, 'grad_norm': 1.42, 'learning_rate': 1.1e-05, 'epoch': 0.62}",
        '```',
        '',
        '**loss** é a cross-entropy nos tokens de resposta. ',
        'Com `assistant_only_loss=True` e `loss_type="nll"`, ela só considera os tokens do assistant.',
        'Menor loss ≈ modelo melhorando em imitar as respostas do dataset.',
        '',
        '**grad_norm** mede a norma dos gradientes. Valores normais: 0.2 ~ 5.0. ',
        'Acima de 50, inf ou nan → treino instável.',
        '',
        '**learning_rate** começa subindo no warmup e decai em cosseno. ',
        'Normal ver variando.',
        '',
        '**epoch** mostra o progresso. `epoch: 0.62` = 62% da primeira época.',
        '',
        '### 2. Métricas de validação (a cada `eval_steps=50`)',
        '',
        '```',
        "{'eval_loss': 1.87, 'eval_runtime': 12.5, 'eval_samples_per_second': 24.1, 'epoch': 0.62}",
        '```',
        '',
        '**eval_loss** é a métrica mais importante. ',
        'Como configuramos `load_best_model_at_end=True` com `metric_for_best_model="eval_loss"`, ',
        'o trainer escolhe o checkpoint com **menor eval_loss**.',
        '',
        'eval_loss caindo = modelo generalizando bem. ',
        'eval_loss subindo + loss de treino caindo = overfitting.',
        '',
        '### 3. Métricas finais (após `trainer.train()`)',
        '',
        '```',
        "{'train_runtime': 320.5, 'train_samples_per_second': 6.0, 'train_loss': 1.42, 'epoch': 3.0}",
        '```',
        '',
        '**train_runtime** é o tempo total em segundos. ',
        '**train_loss** é a loss média final — útil, mas menos importante que eval_loss.',
        '',
        '**No seu script, quem manda é: menor eval_loss.**',
      ].join('\n'),
      rightBody: [
        '## O que observar de verdade',
        '',
        '| Métrica | O que indica |',
        '|---|---|',
        '| **eval_loss** | Qualidade real do modelo 🎯 |',
        '| **loss** | Ajuste ao treino (deve cair) |',
        '| **grad_norm** | Estabilidade (evite >50 ou NaN) |',
        '| **learning_rate** | Scheduler funcionando |',
        '| **train_runtime** | Performance (não qualidade) |',
        '',
        '---',
        '',
        '### Bom sinal ✅',
        '',
        '```',
        'loss:      2.4 → 1.8 → 1.3',
        'eval_loss: 2.5 → 1.9 → 1.5',
        'grad_norm: 1.5 → 2.1 → 1.8',
        '```',
        '',
        'Loss caindo, eval_loss caindo, grad_norm sem explosão.',
        '',
        '### Sinal de overfitting ⚠️',
        '',
        '```',
        'loss:      2.4 → 1.2 → 0.6',
        'eval_loss: 2.5 → 2.6 → 3.1',
        'grad_norm: 1.5 → 3.0 → 5.0',
        '```',
        '',
        'Loss cai muito, eval_loss sobe = modelo decorando o treino.',
        '',
        '---',
        '',
        '### Checklist de leitura',
        '',
        '1. Comece pela **eval_loss**',
        '2. Depois veja se a **loss** está acompanhando',
        '3. Confira o **grad_norm** — sem picos',
        '4. Verifique se **nan** ou **inf** nunca aparecem',
        '5. train_runtime é só para saber quanto tempo levou',
        '',
        '> Lembre-se: no SFT clássico o modelo aprende a prever os próximos tokens ',
        '> das respostas esperadas minimizando negative log-likelihood. ',
        '> Loss menor não é "acurácia" — não garante respostas perfeitas em geração.',
      ].join('\n'),
    },
    'en-us': {
      title: 'SFT Metrics',
      body: [
        'During training, `SFTTrainer` produces 3 metric blocks you need to know how to read.',
        '',
        '### 1. Training metrics (every `logging_steps=50`)',
        '',
        '```',
        "{'loss': 2.314, 'grad_norm': 1.42, 'learning_rate': 1.1e-05, 'epoch': 0.62}",
        '```',
        '',
        '**loss** is cross-entropy on the response tokens. ',
        'With `assistant_only_loss=True` and `loss_type="nll"`, it only considers assistant tokens.',
        'Lower loss ≈ model getting better at imitating dataset responses.',
        '',
        '**grad_norm** measures gradient magnitude. Normal range: 0.2 ~ 5.0. ',
        'Above 50, inf, or NaN → unstable training.',
        '',
        '**learning_rate** warms up then decays via cosine schedule. ',
        'Expected to change.',
        '',
        '**epoch** tracks progress. `epoch: 0.62` = 62% of the first epoch.',
        '',
        '### 2. Validation metrics (every `eval_steps=50`)',
        '',
        '```',
        "{'eval_loss': 1.87, 'eval_runtime': 12.5, 'eval_samples_per_second': 24.1, 'epoch': 0.62}",
        '```',
        '',
        '**eval_loss** is the most important metric. ',
        'Since we set `load_best_model_at_end=True` with `metric_for_best_model="eval_loss"`, ',
        'the trainer picks the checkpoint with the **lowest eval_loss**.',
        '',
        'eval_loss dropping = model generalizing well. ',
        'eval_loss rising + training loss dropping = overfitting.',
        '',
        '### 3. Final metrics (after `trainer.train()`)',
        '',
        '```',
        "{'train_runtime': 320.5, 'train_samples_per_second': 6.0, 'train_loss': 1.42, 'epoch': 3.0}",
        '```',
        '',
        '**train_runtime** is total time in seconds. ',
        '**train_loss** is the average training loss — useful but less important than eval_loss.',
        '',
        '**What matters in your script: lowest eval_loss.**',
      ].join('\n'),
      rightBody: [
        '## What to actually watch',
        '',
        '| Metric | What it tells you |',
        '|---|---|',
        '| **eval_loss** | Real model quality 🎯 |',
        '| **loss** | Training fit (should drop) |',
        '| **grad_norm** | Stability (avoid >50 or NaN) |',
        '| **learning_rate** | Scheduler working |',
        '| **train_runtime** | Performance (not quality) |',
        '',
        '---',
        '',
        '### Good signal ✅',
        '',
        '```',
        'loss:      2.4 → 1.8 → 1.3',
        'eval_loss: 2.5 → 1.9 → 1.5',
        'grad_norm: 1.5 → 2.1 → 1.8',
        '```',
        '',
        'Loss dropping, eval_loss dropping, grad_norm stable.',
        '',
        '### Overfitting warning ⚠️',
        '',
        '```',
        'loss:      2.4 → 1.2 → 0.6',
        'eval_loss: 2.5 → 2.6 → 3.1',
        'grad_norm: 1.5 → 3.0 → 5.0',
        '```',
        '',
        'Loss drops sharply, eval_loss rises = model memorizing training data.',
        '',
        '---',
        '',
        '### Reading checklist',
        '',
        '1. Start with **eval_loss**',
        '2. Check if **loss** follows the same trend',
        '3. Inspect **grad_norm** — no spikes',
        '4. Verify **nan** or **inf** never appear',
        '5. train_runtime is just runtime — not quality',
        '',
        '> Remember: classic SFT minimizes negative log-likelihood ',
        '> of the target sequence. Lower loss is not "accuracy" — ',
        '> it does not guarantee perfect generation output.',
      ].join('\n'),
    },
  },
});
