import { defineSlide } from './_factory';

export const sftFullConfig = defineSlide({
  id: 'sft-full-config',
  type: 'two-column',
  options: { columnRatios: [0.5, 0.5] },
  content: {
    'pt-br': {
      title: 'SFTConfig sem caixa-preta',
      body: [
        '`SFTConfig` é onde o treino deixa de ser “mágica da TRL” e vira configuração explícita do loop.',
        '',
        '### Tamanho do treino',
        '',
        '- `max_steps`: quantos updates o otimizador faz',
        '- `per_device_train_batch_size`: exemplos por GPU antes da acumulação',
        '- `gradient_accumulation_steps`: soma gradientes antes do update',
        '- `max_length`: limite de tokens por conversa renderizada',
        '',
        '### Qualidade do update',
        '',
        '- `learning_rate`: tamanho do passo nos pesos',
        '- `bf16`: reduz memória mantendo boa faixa numérica',
        '- `gradient_checkpointing`: troca compute por menos VRAM',
        '- `assistant_only_loss`: calcula loss só na resposta esperada',
      ].join('\n'),
      rightBody: [
        '### Observabilidade',
        '',
        '- `do_eval=True`: habilita avaliação durante o treino',
        '- `eval_strategy="steps"`: avalia por intervalo de steps',
        '- `eval_steps`: frequência da validação',
        '- `logging_steps`: frequência dos logs de treino',
        '- `save_strategy="no"`: evita checkpoints intermediários no exemplo',
        '- `report_to="none"`: não envia métricas para serviços externos',
        '- `remove_unused_columns=False`: preserva `messages` para o pipeline conversacional',
        '',
        'A validação do smoke não é benchmark final. Ela existe para confirmar que o pipeline treina e que a loss de eval acompanha o movimento do treino curto.',
      ].join('\n'),
    },
    'en-us': {
      title: 'SFTConfig without black box',
      body: [
        '`SFTConfig` is where training stops looking like “TRL magic” and becomes an explicit loop configuration.',
        '',
        '### Training size',
        '',
        '- `max_steps`: how many optimizer updates to run',
        '- `per_device_train_batch_size`: examples per GPU before accumulation',
        '- `gradient_accumulation_steps`: accumulate gradients before one update',
        '- `max_length`: token limit per rendered conversation',
        '',
        '### Update quality',
        '',
        '- `learning_rate`: step size applied to weights',
        '- `bf16`: saves memory while keeping useful numeric range',
        '- `gradient_checkpointing`: trades compute for lower VRAM',
        '- `assistant_only_loss`: computes loss only on the expected answer',
      ].join('\n'),
      rightBody: [
        '### Observability',
        '',
        '- `do_eval=True`: enables evaluation during training',
        '- `eval_strategy="steps"`: evaluates by step interval',
        '- `eval_steps`: validation frequency',
        '- `logging_steps`: training log frequency',
        '- `save_strategy="no"`: avoids intermediate checkpoints in the example',
        '- `report_to="none"`: does not send metrics to external services',
        '- `remove_unused_columns=False`: preserves `messages` for the conversational pipeline',
        '',
        'Smoke validation is not a final benchmark. It exists to confirm the pipeline trains and that eval loss follows the short training run.',
      ].join('\n'),
    },
  },
});
